// This file is managed by Lisa and IS replaced on each `lisa` run.
// Do not edit directly — durable changes belong upstream in Lisa.

/** Static entrypoints and deterministic feature-local document rendering. */
import { byCodeUnit } from "./contract.mjs";
import { cell } from "./markdown-cell.mjs";
import {
  featureArtifactPaths,
  FEATURE_PROJECTION_SCHEMA,
} from "./projection-paths.mjs";

export const PROJECTION_INDEX_SCHEMA = "lisa-bdd-projection-index-v1";
export const MATRIX_COMMAND =
  'BDD_BASE_SHA="$(git merge-base HEAD origin/HEAD)" bun run bdd:matrix';
export const COVERAGE_COMMAND =
  'BDD_BASE_SHA="$(git merge-base HEAD origin/HEAD)" bun run bdd:coverage:write';
export const REPORT_COMMAND =
  'BDD_BASE_SHA="$(git merge-base HEAD origin/HEAD)" node scripts/check-bdd-coverage.mjs --report';
export const AGGREGATE_MATRIX_COMMAND = "node scripts/bdd-matrix.mjs";
const COMMAND_CONTEXT =
  "The node scripts/... examples use installed host paths. In the Lisa monorepo, use BDD_COVERAGE_ROOT=. and the expo/copy-overwrite/scripts/ prefix instead; the coverage report still requires BDD_BASE_SHA.";

/** Sort object properties recursively; retain meaningful ordered arrays. */
function stableValue(value) {
  if (Array.isArray(value)) return value.map(stableValue);
  if (value === null || typeof value !== "object") return value;
  return Object.fromEntries(
    Object.keys(value)
      .sort(byCodeUnit)
      .map(key => [key, stableValue(value[key])])
  );
}

/** Complete records remain machine-readable without generation timestamps. */
export const projectionJson = value =>
  `${JSON.stringify(stableValue(value), null, 2)}\n`;

/** Keep table data inert, including HTML, Markdown links and code delimiters. */
export const projectionCell = value =>
  cell(
    String(value ?? "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/`/g, "&#96;")
      .replace(/\[/g, "&#91;")
      .replace(/\]/g, "&#93;")
  );

/** A bounded, encoded ownership marker cannot be terminated by source text. */
export const projectionMarker = (sourceFile, kind) =>
  `<!-- ${FEATURE_PROJECTION_SCHEMA} ${kind} source=${encodeURIComponent(sourceFile)} -->`;

export const STATIC_ARTIFACTS = new Map([
  [
    "bdd/coverage-report.json",
    projectionJson({
      schemaVersion: PROJECTION_INDEX_SCHEMA,
      generator: "lisa-bdd-feature-projection",
      featureReports: "bdd/reports/v1/features/",
      scenarioMatrices: "docs/bdd-scenario-matrix/",
      coverageDocuments: "docs/e2e-bdd-coverage/",
      sourceIdentity: "Full repository-relative bdd/features/*.feature path",
      commandContext: COMMAND_CONTEXT,
      commands: { matrix: MATRIX_COMMAND, coverage: COVERAGE_COMMAND },
      aggregateCommands: {
        matrix: AGGREGATE_MATRIX_COMMAND,
        coverage: REPORT_COMMAND,
      },
      aggregate:
        "The aggregate matrix displays declared mappings. The --report runtime report and feature leaves validate evidence resolution; CI publishes the global summary.",
    }),
  ],
  [
    "docs/bdd-scenario-matrix.md",
    `# BDD scenario traceability matrix

Generated by \`${MATRIX_COMMAND}\`; never hand-edited.

Feature documents live under [bdd-scenario-matrix/](bdd-scenario-matrix/), using the complete repository-relative source path as their suffix. Their matching JSON records live under [../bdd/reports/v1/features/](../bdd/reports/v1/features/).

Each document preserves its declarations, tracker references, mapped evidence and supplied execution outcomes. Traceability proves automation exists; it never proves that automation ran or passed. Waivers are never coverage.

${COMMAND_CONTEXT}

Run \`${AGGREGATE_MATRIX_COMMAND}\` for the current aggregate matrix. Its mapping cells display declared, configured mappings; they do not validate that each evidence title still exists. Evidence-resolution credit comes from the feature leaves and \`${REPORT_COMMAND}\`. CI publishes current global counts and the full runtime coverage summary. This entrypoint intentionally stores no feature list or global counts.
`,
  ],
  [
    "docs/e2e-bdd-coverage.md",
    `# BDD behavior contract — coverage burndown

Generated from \`bdd/features/*.feature\` and \`bdd/coverage-map.json\`.
Regenerated by \`${COVERAGE_COMMAND}\`; never hand-edited.

## What each number means

Traceability coverage reports aligned mappings with evidence still present. **This is not execution coverage and not a pass rate.** Supplied execution outcomes remain separate. A waiver is an owned, dated IOU outside the obligation denominator; it is never coverage.

Feature documents live under [e2e-bdd-coverage/](e2e-bdd-coverage/) with the complete source path as their suffix. Complete local records live under [../bdd/reports/v1/features/](../bdd/reports/v1/features/).

${COMMAND_CONTEXT}

Run \`${REPORT_COMMAND}\` for the current full runtime report. \`node scripts/check-bdd-coverage.mjs --report\` also emits diagnostic JSON, but can exit nonzero when a required baseline is absent or validation finds defects. CI publishes global counts, discovered-test inventory, floor evaluations and defects. Unassociated retirement records remain in \`bdd/coverage-map.json\`. This entrypoint intentionally stores no feature list or global counts.
`,
  ],
]);

/** Fixed headers keep author text exclusively inside escaped cells. */
function table(headers, rows) {
  const body = rows.length
    ? rows.map(row => `| ${row.map(projectionCell).join(" | ")} |`).join("\n")
    : `| ${headers.map(() => "—").join(" | ")} |`;
  return `| ${headers.join(" | ")} |\n|${headers.map(() => "---").join("|")}|\n${body}`;
}

/** Preserve every mapped string and its genuine evidence verdict. */
function mappingTable(scenarios) {
  return table(
    [
      "Scenario",
      "Runner",
      "Platforms",
      "File",
      "Evidence",
      "Evidence resolution",
      "Execution",
      "Run",
    ],
    scenarios.flatMap(row =>
      row.mappings.map(mapping => [
        row.id,
        mapping.runner,
        mapping.platforms.join(", "),
        mapping.file,
        mapping.evidence,
        mapping.evidenceResolution.ok
          ? "resolved"
          : `invalid: ${mapping.evidenceResolution.detail}`,
        mapping.execution.status,
        mapping.execution.runId,
      ])
    )
  );
}

/** Declaration facts include ordered primary steps and complete tag scopes. */
function declarationTables(scenarios) {
  return table(
    [
      "Scenario",
      "Behavior",
      "Feature",
      "Source line",
      "Platforms",
      "Lifecycle",
      "Tags",
      "Steps",
    ],
    scenarios.map(row => [
      row.id,
      row.name,
      row.feature,
      row.line,
      row.platforms.join(", "),
      row.required ? "required" : row.lifecycle.join(", "),
      row.tags.join(", "),
      row.primarySteps.join("; "),
    ])
  );
}

/** Human-readable references remain separate from executable evidence. */
function trackerTable(scenarios) {
  return table(
    ["Scenario", "Reference", "URL"],
    scenarios.flatMap(row =>
      row.trackers.map(reference => [
        row.id,
        reference.tag,
        reference.url ?? "No URL template declared",
      ])
    )
  );
}

/** Waiver compatibility retains the original seven-column contract. */
function waiverSection(scenarios) {
  const entries = scenarios.flatMap(row => row.waivers);
  const ledger = table(
    ["Scenario", "Platforms", "Runner", "Owner", "Reason", "Ticket", "Expires"],
    entries.map(entry => [
      entry.scenario,
      Array.isArray(entry.platforms)
        ? entry.platforms.join(", ")
        : entry.platforms,
      entry.runner,
      entry.owner,
      entry.reason,
      entry.ticket,
      entry.expiresAt,
    ])
  );
  const dates = table(
    ["Scenario", "Recorded at"],
    entries.map(entry => [entry.scenario, entry.recordedAt])
  );
  return `${ledger}\n\nWaiver recording dates (complete records are retained in JSON):\n\n${dates}`;
}

/** Retirement fields stay readable; unrelated retirements remain input-owned. */
function retirementTable(scenarios) {
  return table(
    ["Scenario", "Platforms", "Approved by", "Reason", "Ticket", "Recorded at"],
    scenarios
      .flatMap(row => row.retirements)
      .map(entry => [
        entry.scenario,
        Array.isArray(entry.platforms)
          ? entry.platforms.join(", ")
          : entry.platforms,
        entry.approvedBy,
        entry.reason,
        entry.ticket,
        entry.recordedAt,
      ])
  );
}

/** Local obligations never claim execution credit or turn waivers into proof. */
function obligationTable(scenarios) {
  return table(
    [
      "Scenario",
      "Platform",
      "Configured runners",
      "Traceability",
      "Waived",
      "Gap",
    ],
    scenarios.flatMap(row =>
      row.obligations.map(value => [
        row.id,
        value.platform,
        value.runners.join(", "),
        value.covered ? "covered" : "uncovered",
        value.waived ? "yes" : "no",
        value.gap ? "yes" : "no",
      ])
    )
  );
}

/** Both leaf documents carry the same local facts without a global roster. */
function localDocument(model, kind) {
  const title =
    kind === "matrix"
      ? "BDD scenario traceability matrix"
      : "BDD behavior contract — feature coverage burndown";
  return `${projectionMarker(model.sourceFile, kind)}
# ${title}

Source: ${projectionCell(model.sourceFile)}

Traceability proves aligned automation exists, never that it ran or passed. A waiver is never coverage. Execution marked “not supplied” is unknown; “not run” means no supplied result matched this mapping. Retry outcomes retain the worst supplied result.

## Declarations

${declarationTables(model.scenarios)}

## Tracker references

${trackerTable(model.scenarios)}

## Mapped evidence and execution

${mappingTable(model.scenarios)}

## Local obligations

${obligationTable(model.scenarios)}

## Waived obligations

${waiverSection(model.scenarios)}

## Associated retirements

${retirementTable(model.scenarios)}

The matching JSON leaf retains complete local declarations, mappings, waiver and retirement records. Current global inventory, counts, floor evaluations and defects are published by the runtime CI summary.
`;
}

/** Render all three canonical leaves for one source identity. */
export function renderFeatureArtifacts(model) {
  const [json, matrix, coverage] = featureArtifactPaths(model.sourceFile);
  return new Map([
    [json, projectionJson(model)],
    [matrix, localDocument(model, "matrix")],
    [coverage, localDocument(model, "coverage")],
  ]);
}
