/**
 * Regression coverage for the *documented* run-recorder invocation (#3433).
 *
 * `automation-runbook-contract` makes a run that stops without recording its
 * outcome a contract violation, so the command the loop skills print is
 * load-bearing: an operator or an agent copies it verbatim. It was dead.
 * `CLAUDE_PLUGIN_ROOT` is not exported into an agent Bash tool environment, so
 * `"${CLAUDE_PLUGIN_ROOT}/scripts/automation-run-record.mjs"` expanded to the
 * absolute `/scripts/automation-run-record.mjs` and exited 1, and the two
 * documented fallbacks (`plugins/lisa/scripts/...`, `plugins/src/base/scripts/...`)
 * resolve against the Lisa *package* root while a loop runs from the *consumer
 * repository* root, where neither exists.
 *
 * The fix reuses the portable parameter chain already proven for the wiki
 * resolver (see `wiki-ensure-wiki.test.ts`): runtime plugin roots first, then
 * the installed package copy under `$(npm root)`.
 *
 * These tests cover both halves — that every shipped copy of every recording
 * skill carries the portable command, and that the command actually resolves
 * from a consumer-shaped repository root.
 * @module tests/unit/strategies/automation-run-record-invocation
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { boundedSpawnSync } from "../../helpers/io-latency-budget.js";

/** Pinned interpreter — resolving `bash` via $PATH trips no-os-command-from-path. */
const BASH = "/bin/bash";

/**
 * The exact command the skills document, byte for byte.
 *
 * Asserted as a literal rather than assembled, so a future edit that changes
 * the resolution order has to change this test too.
 */
const PORTABLE_COMMAND =
  'node "${PLUGIN_ROOT:-${CLAUDE_PLUGIN_ROOT:-${CURSOR_PLUGIN_ROOT:-$(npm root)/@codyswann/lisa/plugins/lisa}}}/scripts/automation-run-record.mjs"';

/** The dead form this ticket removed. Must not reappear in any shipped copy. */
const DEAD_COMMAND =
  'node "${CLAUDE_PLUGIN_ROOT}/scripts/automation-run-record.mjs"';

/** Sentinel phrase of the dead two-path fallback paragraph. */
const DEAD_FALLBACK = "resolve the plugin scripts directory directly";

/**
 * Every shipped projection of the base plugin.
 *
 * `plugins/src/base` is canonical; the rest are generated by `build:plugins`
 * and are what consumers actually install, so the fix has to be present in all
 * of them or some agent still reads the dead command.
 */
const BASE_PLUGIN_ROOTS = [
  "plugins/src/base",
  "plugins/lisa",
  "plugins/lisa/.codex-plugin",
  "plugins/lisa-agy",
  "plugins/lisa-copilot",
  "plugins/lisa-cursor",
] as const;

/** The registered-loop skills that record a run outcome via the recorder. */
const RECORDING_SKILLS = [
  "lisa-intake",
  "lisa-monitor",
  "lisa-exploratory-qa",
  "lisa-learnings-audit",
  "lisa-project-ideation",
  "lisa-repair-intake",
] as const;

/** Recorder filename, shared by the fixture and the assertions. */
const RECORDER = "automation-run-record.mjs";
/** Sibling module the recorder imports; the fixture is unusable without it. */
const DENOMINATOR_MODULE = "intake-prework-denominator.mjs";
/** Package-relative scripts directory inside an installed copy of Lisa. */
const PACKAGE_SCRIPTS = "node_modules/@codyswann/lisa/plugins/lisa/scripts";
/** Loop id used by the recording probes. */
const LOOP = "monitor";
/** Runbook path passed to the recorder; it need not exist to record a row. */
const RUNBOOK = ".lisa/automations/monitor.runbook.md";
/** JSONL surface the recorder writes, relative to the project root. */
const RECORDS = ".lisa/automations/runs/monitor.jsonl";

/** Consumer-shaped fixture root: has node_modules, no Lisa checkout. */
let consumer: string;
/** Bare root with no node_modules at all — isolates the default branch. */
let bare: string;
/** Absolute plugin root inside the fixture, for the export-wins probe. */
let installedPluginRoot: string;

beforeAll(() => {
  consumer = mkdtempSync(path.join(tmpdir(), "lisa-record-consumer-"));
  bare = mkdtempSync(path.join(tmpdir(), "lisa-record-bare-"));

  const scripts = path.join(consumer, PACKAGE_SCRIPTS);
  mkdirSync(scripts, { recursive: true });
  for (const file of [RECORDER, DENOMINATOR_MODULE]) {
    copyFileSync(
      path.resolve("plugins/lisa/scripts", file),
      path.join(scripts, file)
    );
  }
  installedPluginRoot = path.dirname(scripts);
});

afterAll(() => {
  for (const dir of [consumer, bare]) {
    rmSync(dir, { recursive: true, force: true });
  }
});

/**
 * Run a shell snippet with every plugin-root variable cleared, then re-applied
 * from `env`, so each probe controls exactly which rung of the chain is live.
 * @param script - Shell source to execute.
 * @param cwd - Working directory for the invocation.
 * @param env - Plugin-root variables to export for this probe.
 * @returns The child's exit status, defaulting to 1 when it was signalled.
 */
const runShell = (
  script: string,
  cwd: string,
  env: Readonly<Record<string, string>> = {}
): number => {
  const childEnv = { ...process.env, ...env };
  for (const key of [
    "PLUGIN_ROOT",
    "CLAUDE_PLUGIN_ROOT",
    "CURSOR_PLUGIN_ROOT",
  ]) {
    if (!(key in env)) delete childEnv[key];
  }
  const result = boundedSpawnSync({
    label: "documented run-record invocation",
    command: BASH,
    args: ["-c", script],
    cwd,
    env: childEnv,
  });
  return result.status ?? 1;
};

/**
 * Build the documented invocation with a full, valid argument list.
 * @param summary - Operator-readable one-liner recorded on the row.
 * @param command - Invocation prefix; defaults to the documented one.
 * @returns A shell snippet that records one run outcome.
 */
const recordRun = (summary: string, command = PORTABLE_COMMAND): string =>
  `${command} --loop-id ${LOOP} --outcome change-proved ` +
  `--summary ${JSON.stringify(summary)} --runbook ${RUNBOOK}`;

describe("documented run-recorder invocation is present in every shipped copy", () => {
  it.each(
    BASE_PLUGIN_ROOTS.flatMap(root =>
      RECORDING_SKILLS.map(skill => [root, skill] as const)
    )
  )("%s/skills/%s documents the portable command", (root, skill) => {
    const content = readFileSync(
      path.join(root, "skills", skill, "SKILL.md"),
      "utf8"
    );

    expect(content).toContain(PORTABLE_COMMAND);
    expect(content).not.toContain(DEAD_COMMAND);
    expect(content).not.toContain(DEAD_FALLBACK);
  });

  it("covers all six projections of all six recording skills", () => {
    const files = BASE_PLUGIN_ROOTS.flatMap(root =>
      RECORDING_SKILLS.map(skill =>
        path.join(root, "skills", skill, "SKILL.md")
      )
    );

    expect(files).toHaveLength(36);
    expect(files.filter(file => existsSync(file))).toHaveLength(36);
  });
});

describe("documented run-recorder invocation resolves for real", () => {
  it("records a run from a consumer repo root with no plugin root exported", () => {
    const status = runShell(
      recordRun("Recorded from a consumer root."),
      consumer
    );

    expect(status).toBe(0);
    expect(existsSync(path.join(consumer, RECORDS))).toBe(true);
  });

  it("honours an exported CLAUDE_PLUGIN_ROOT instead of the package default", () => {
    // `bare` has no node_modules, so the `$(npm root)` default cannot resolve
    // here. Succeeding proves the exported value is what was used.
    const withExport = runShell(
      recordRun("Recorded via the exported root."),
      bare,
      {
        CLAUDE_PLUGIN_ROOT: installedPluginRoot,
      }
    );
    const withoutExport = runShell(recordRun("Should not resolve."), bare);

    expect(withExport).toBe(0);
    expect(withoutExport).not.toBe(0);
  });

  it("BITE CONTROL: a wrong recorder path still fails loudly", () => {
    const status = runShell(
      recordRun(
        "Never recorded.",
        `node "${installedPluginRoot}/scripts/not-${RECORDER}"`
      ),
      consumer
    );

    expect(status).not.toBe(0);
  });
});
