---
detectors:
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 10
  TooManyInstanceVariables:
    max_instance_variables: 6
  TooManyMethods:
    max_methods: 15
  UtilityFunction:
    public_methods_only: true
  FeatureEnvy:
    enabled: true
  LongParameterList:
    max_params: 4

directories:
  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  'app/helpers':
    UtilityFunction:
      enabled: false
  'app/jobs':
    UtilityFunction:
      enabled: false
  'db/migrate':
    IrresponsibleModule:
      enabled: false
    FeatureEnvy:
      enabled: false
