/** Graph data uses genuine parser/source bytes and never grants provider or runtime authority. */
import { describe, expect, it } from "vitest";
import {
  mkdtempSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  rmSync,
  symlinkSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import {
  auditedHelperEdges,
  generatedHelperGraph,
} from "../../../scripts/generate-npm-updater-helper-graph.mjs";
import {
  managedTemplateMembers,
  classifierGraphMatches,
} from "../../../all/copy-overwrite/scripts/lib/npm-update-helper-graph.mjs";

describe("literal canonical classifier qualification", () => {
  const literal =
    'import { isPreWorkLaneType } from "./intake-prework-denominator.mjs";';
  const classify = (
    first: string,
    second = "export function isPreWorkLaneType() {}"
  ) => classifierGraphMatches([Buffer.from(first), Buffer.from(second)]);
  it("retains the one exact dependency and ordinary exported declarations", () => {
    expect(classify(`${literal}\nexport function humanGateVerdict() {}`)).toBe(
      true
    );
  });
  it.each([
    'import "./extra.mjs";',
    'import\n{ value } from "./extra.mjs";',
    'export { value }\nfrom "./extra.mjs";',
    'export * from "./extra.mjs";',
    'const foreign = import("./extra.mjs");',
    'export const marker = 1; export { value } from "./extra.mjs";',
    'export function local() {} export { value } from "./extra.mjs";',
    'const marker = 1; export { value } from "./extra.mjs";',
    'const marker = 1; import { value } from "./extra.mjs";',
  ])("refuses additional import/re-export authority: %s", extra => {
    expect(classify(`${literal}\n${extra}`)).toBe(false);
    expect(classify(literal, extra)).toBe(false);
  });
});

async function sourceFixture(
  operation: (root: string, first: string) => Promise<void>
) {
  const root = mkdtempSync(join(tmpdir(), "lisa-helper-generator-"));
  const files = [
    ...managedTemplateMembers().values(),
    "plugins/lisa/scripts/intake-blocker-reprobe.mjs",
    "plugins/lisa/scripts/intake-prework-denominator.mjs",
  ];
  try {
    for (const file of files) {
      mkdirSync(dirname(join(root, file)), { recursive: true });
      writeFileSync(join(root, file), readFileSync(file));
    }
    await operation(root, files[0]!);
  } finally {
    rmSync(root, { recursive: true });
  }
}

describe("reproducible updater helper graph", () => {
  it("reproduces the complete generated bytes from actual source and parser coordinates", async () => {
    expect(await generatedHelperGraph(process.cwd())).toEqual(
      readFileSync("all/copy-overwrite/scripts/npm-updater-helper-graph.json")
    );
  });
  it("refuses new nonliteral imports instead of silently blessing an unbounded helper edge", async () => {
    await expect(
      auditedHelperEdges(
        "lib/npm-update-helper.mjs",
        Buffer.from("await import(candidate);")
      )
    ).rejects.toThrow(/nonliteral/);
    await expect(
      auditedHelperEdges(
        "lisa-work-item.mjs",
        Buffer.from("await import(candidate);")
      )
    ).rejects.toThrow(/nonliteral/);
  });
  it("refuses aliased or missing source rather than taking a released fallback", async () => {
    await sourceFixture(async (root, first) => {
      const path = join(root, first),
        target = join(root, "alias-target.mjs");
      writeFileSync(target, readFileSync(path));
      rmSync(path);
      symlinkSync(target, path);
      await expect(generatedHelperGraph(root)).rejects.toThrow(/aliased/);
      rmSync(path);
      await expect(generatedHelperGraph(root)).rejects.toThrow(/ENOENT/);
    });
  });
});
