/** Commit preparation repairs authored references without changing validation. */
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { afterAll, afterEach, describe, expect, it } from "vitest";

import { LANE_ID_VARIABLES } from "../../../all/copy-overwrite/scripts/lisa-work-item.mjs";

import {
  bindTo,
  cleanupFixtures,
  cleanupTemplates,
  cli,
  git,
  offlineFixture,
  REF,
  OTHER_REF,
} from "../../support/work-item-cli.js";

const PREPARE = "prepare-commit-msg";
const TRAILER = `Work-Item: ${REF}`;
const COAUTHOR = "Co-authored-by: Contributor <contributor@example.test>";
const NO_LANE = Object.fromEntries(
  LANE_ID_VARIABLES.map((variable: string) => [variable, ""])
);
const STRANDED = [
  `${TRAILER}\n\nGenerated by an agent\n\n${COAUTHOR}`,
  `${TRAILER}\n\n${COAUTHOR}`,
  `${TRAILER}\nRefs #42\n${COAUTHOR}`,
  `${TRAILER}\n${COAUTHOR}\nGenerated with a coding agent`,
];

afterEach(cleanupFixtures);
afterAll(cleanupTemplates);

describe.each([false, true])("authored trailers with binding=%s", bound => {
  it.each(STRANDED)("repairs a stranded reference: %s", tail => {
    const fixture = offlineFixture();
    if (bound) bindTo(fixture, REF);
    const file = path.join(fixture.root, "MSG");
    const original = `fix: preserve this subject\n\n${tail}\n`;
    writeFileSync(file, original);
    const parse = () =>
      git(fixture.root, ["interpret-trailers", "--parse", file], fixture.env);
    expect(parse()).not.toContain(TRAILER);

    expect(cli(fixture, [PREPARE, file], NO_LANE).exitCode).toBeUndefined();

    expect(parse()).toContain(TRAILER);
    expect(readFileSync(file, "utf8")).toContain(original.trimEnd());
    const prepared = readFileSync(file, "utf8");
    expect(cli(fixture, [PREPARE, file], NO_LANE).exitCode).toBeUndefined();
    expect(readFileSync(file, "utf8")).toBe(prepared);
  });
});

describe("authored trailer controls", () => {
  it("keeps an already parseable reference single", () => {
    const fixture = offlineFixture();
    const file = path.join(fixture.root, "MSG");
    const original = `fix: keep\n\n${TRAILER}\n${COAUTHOR}\n`;
    writeFileSync(file, original);
    cli(fixture, [PREPARE, file], NO_LANE);
    expect(readFileSync(file, "utf8")).toBe(original);
  });

  it.each([
    "fix: no reference\n",
    `fix: ambiguous\n\n${TRAILER}\nWork-Item: ${OTHER_REF}\n`,
    "fix: invalid\n\nWork-Item: not-a-reference\n",
  ])("leaves an absent or invalid selection for validation: %s", original => {
    const fixture = offlineFixture();
    const file = path.join(fixture.root, "MSG");
    writeFileSync(file, original);
    expect(cli(fixture, [PREPARE, file], NO_LANE).exitCode).toBeUndefined();
    expect(readFileSync(file, "utf8")).toBe(original);
  });

  it("does not repair an authored reference on a merge", () => {
    const fixture = offlineFixture();
    const file = path.join(fixture.root, "MSG");
    const original = `Merge branch 'main'\n\n${STRANDED[0]}\n`;
    writeFileSync(file, original);
    cli(fixture, [PREPARE, file, "merge"], NO_LANE);
    expect(readFileSync(file, "utf8")).toBe(original);
  });

  it.each([undefined, "{", "{}"])(
    "keeps an unbound message when configuration is unavailable: %s",
    config => {
      const fixture = offlineFixture();
      const settings = path.join(fixture.root, ".lisa.config.json");
      if (config === undefined) rmSync(settings);
      else writeFileSync(settings, config);
      const file = path.join(fixture.root, "MSG");
      const original = `fix: keep\n\n${STRANDED[0]}\n`;
      writeFileSync(file, original);
      expect(cli(fixture, [PREPARE, file], NO_LANE).exitCode).toBeUndefined();
      expect(readFileSync(file, "utf8")).toBe(original);
    }
  );
});
