/**
 * What the session-start hook is responsible for running.
 *
 * A cloud environment skips its setup script whenever a filesystem cache
 * exists, so anything that only runs there goes stale: it is re-run when the
 * vendor's setup field changes, or after roughly seven days, and not otherwise.
 *
 * This hook is part of the clone rather than the snapshot, which makes it the
 * one place that runs on every session regardless of cache state. The secrets
 * phase already lived here for that reason. The toolchain had the same
 * staleness problem and no answer to it — a tool added to `remoteEnv.tools` was
 * invisible to a cached container, so a pin could be merged, correct, and
 * simply absent from the next session.
 * @module tests/unit/secrets/remote-env-session-start-hook
 */
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { boundedSpawnSync } from "../../helpers/io-latency-budget.js";

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe("session-start hook covers the toolchain too", () => {
  const TOOLCHAIN_PHASE = "--phase=toolchain";
  const SECRETS_PHASE = "--phase=secrets";
  const HOOK_PHASE = "--phase=hook";
  const HOOK = readFileSync(
    "plugins/src/base/skills/lisa-setup-remote-env/assets/session-start.sh",
    "utf8"
  );

  it("runs the toolchain phase, not only secrets", () => {
    // The toolchain used to run only from the environment setup script, which a
    // cached environment SKIPS. A tool added to remoteEnv.tools was therefore
    // invisible until the cache expired about a week later, or until someone
    // edited the vendor's setup field by hand to force a rebuild — so a
    // container could be missing a tool its own committed config pins.
    //
    // This hook is part of the clone, so it is the one place that runs every
    // session regardless of cache state.
    expect(HOOK).toContain(TOOLCHAIN_PHASE);
    expect(HOOK).toContain(SECRETS_PHASE);
    expect(HOOK).toContain(HOOK_PHASE);
  });

  it("installs the toolchain before materializing secrets", () => {
    // Materializing needs the provider CLI the toolchain step installs. Run the
    // other way round, a missing binary is reported as a missing credential.
    expect(HOOK.indexOf(TOOLCHAIN_PHASE)).toBeLessThan(
      HOOK.indexOf(SECRETS_PHASE)
    );
    expect(HOOK.indexOf(SECRETS_PHASE)).toBeLessThan(HOOK.indexOf(HOOK_PHASE));
    // `set -e` makes the first two phases fatal. The final phase is exec'd so
    // its non-zero status reaches the fail-open SessionStart host for display.
    expect(HOOK).toContain(
      'exec /bin/bash "${here}/setup.sh" --phase=hook "$@"'
    );
  });

  it("still does nothing at all on a developer machine", () => {
    // The hook is committed, so it fires on every local session too. Doing the
    // remote work there would be noise on every single startup.
    expect(HOOK).toContain('if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]');
  });

  it("carries the installed PATH into secrets and materialized env into the project hook", () => {
    const root = mkdtempSync(path.join(tmpdir(), "lisa-session-phases-"));
    roots.push(root);
    const home = path.join(root, "home");
    const scripts = path.join(root, "scripts");
    mkdirSync(home, { recursive: true });
    mkdirSync(scripts, { recursive: true });
    writeFileSync(path.join(scripts, "session-start.sh"), HOOK);
    writeFileSync(
      path.join(scripts, "materialized-env-authority.mjs"),
      readFileSync(
        "plugins/src/base/skills/lisa-setup-remote-env/assets/" +
          "materialized-env-authority.mjs"
      ),
      { mode: 0o700 }
    );
    writeFileSync(
      path.join(scripts, "setup.sh"),
      [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        'case "$1" in',
        "  --phase=toolchain)",
        '    mkdir -p "$HOME/.local/bin"',
        "    printf '#!/usr/bin/env bash\\nexit 0\\n' > \"$HOME/.local/bin/provider-cli\"",
        '    chmod +x "$HOME/.local/bin/provider-cli"',
        "    ;;",
        "  --phase=secrets)",
        "    command -v provider-cli >/dev/null",
        '    mkdir -p "$HOME/.config/lisa"',
        '    chmod 700 "$HOME/.config/lisa"',
        "    printf '%s\\n' \\",
        "      '# Generated by lisa-secrets-access. Contains secret values.' \\",
        "      '# Do not print, inspect, summarize, commit, or copy this file.' \\",
        "      \"export LISA_FRESH_SECRET='fresh'\" \\",
        '      > "$HOME/.config/lisa/secrets.env"',
        '    chmod 600 "$HOME/.config/lisa/secrets.env"',
        "    ;;",
        "  --phase=hook)",
        '    [ "${LISA_FRESH_SECRET:-}" = "fresh" ]',
        "    printf 'phase-environment-carried\\n'",
        "    ;;",
        "esac",
        "",
      ].join("\n")
    );

    const run = boundedSpawnSync({
      label: "the session-start phase inheritance fixture",
      command: "/bin/bash",
      args: [path.join(scripts, "session-start.sh")],
      env: {
        CLAUDE_CODE_REMOTE: "true",
        HOME: home,
        PATH: `${path.dirname(process.execPath)}:/usr/bin:/bin`,
      },
    });

    expect(run.status).toBe(0);
    expect(run.stdout).toContain("phase-environment-carried");
  });
});
