/**
 * Executable authority binding for the materialized remote environment.
 *
 * Pure owner checks are necessary but insufficient: the shipped CLI must call
 * that exact default validator when SessionStart executes it. These REDs drive
 * the exported CLI with immutable filesystem facts, then pin its executable
 * guard to the same driver so a parallel or dead predicate cannot pass.
 * @module tests/unit/secrets/remote-env-materialized-cli-driver
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { describe, expect, it } from "vitest";

import { boundedSpawnSync } from "../../helpers/io-latency-budget.js";

/** Minimal immutable lstat result consumed by the authority CLI. */
interface AuthorityStat {
  readonly mode: number;
  readonly uid: number;
  readonly isDirectory: () => boolean;
  readonly isFile: () => boolean;
  readonly isSymbolicLink: () => boolean;
}

/** Test-owned filesystem and diagnostic boundary for one CLI invocation. */
interface AuthorityCliDependencies {
  readonly getuid: () => number;
  readonly lstat: (file: string) => AuthorityStat;
  readonly readFile: (file: string, encoding: "utf8") => string;
  readonly writeError: (diagnostic: string) => void;
}

/** Public executable contract shared by canonical and installed layouts. */
interface AuthorityCliModule {
  readonly runMaterializedEnvAuthorityCli: (
    argv: readonly string[],
    dependencies?: AuthorityCliDependencies
  ) => number;
}

/** One independently imported production authority layout. */
interface AuthorityLayout {
  readonly label: string;
  readonly path: string;
}

const LAYOUTS: readonly AuthorityLayout[] = [
  {
    label: "plugin-sibling",
    path: path.resolve(
      "plugins/src/base/skills/lisa-setup-remote-env/assets/" +
        "materialized-env-authority.mjs"
    ),
  },
  {
    label: "fresh-installed",
    path: path.resolve(
      "scripts/lisa-remote-env/materialized-env-authority.mjs"
    ),
  },
];

const VALUES_FILE = "/authority-fixture/session/secrets.env";
const VALUES_DIRECTORY = path.dirname(VALUES_FILE);
const ENVFILE_MODULE = path.resolve(
  "plugins/src/base/skills/lisa-secrets-access/scripts/envfile.mjs"
);
const VALID_ARTIFACT =
  "# Generated by lisa-secrets-access. Contains secret values.\n" +
  "# Do not print, inspect, summarize, commit, or copy this file.\n" +
  "export LISA_FRESH_SECRET='value-never-printed'\n";
const EXECUTABLE_DRIVER_CALL = new RegExp(
  "process\\.exitCode\\s*=\\s*runMaterializedEnvAuthorityCli\\(" +
    "\\s*process\\.argv\\.slice\\(2\\)\\s*\\)",
  "gu"
);

/**
 * Create one frozen regular-file or directory identity.
 * @param type - Filesystem object kind represented by the frozen stat.
 * @param uid - Numeric owner recorded by the frozen stat.
 * @returns Immutable authority facts for one filesystem object.
 */
function authorityStat(type: "directory" | "file", uid: number): AuthorityStat {
  return Object.freeze({
    mode: type === "directory" ? 0o40700 : 0o100600,
    uid,
    isDirectory: () => type === "directory",
    isFile: () => type === "file",
    isSymbolicLink: () => false,
  });
}

/** Captured behavior from one dependency-injected CLI run. */
interface CliObservation {
  readonly dependencies: AuthorityCliDependencies;
  readonly diagnostics: string[];
  readonly events: string[];
  readonly file: AuthorityStat;
  readonly directory: AuthorityStat;
}

/**
 * Build frozen dependencies whose only authority is supplied lstat facts.
 * @param fileUid - Owner to expose for the values file.
 * @returns Captured dependencies, diagnostics, events, and identity facts.
 */
function observation(fileUid = 501): CliObservation {
  const expectedUid = 501;
  const directory = authorityStat("directory", expectedUid);
  const file = authorityStat("file", fileUid);
  const diagnostics: string[] = [];
  const events: string[] = [];
  const dependencies = Object.freeze({
    getuid: () => {
      events.push("getuid");
      return expectedUid;
    },
    lstat: (candidate: string) => {
      events.push(`lstat:${candidate}`);
      if (candidate === VALUES_DIRECTORY) return directory;
      if (candidate === VALUES_FILE) return file;
      throw new Error(`unexpected lstat path: ${candidate}`);
    },
    readFile: (candidate: string, encoding: "utf8") => {
      events.push(`read:${candidate}:${encoding}`);
      if (candidate !== VALUES_FILE || encoding !== "utf8") {
        throw new Error(`unexpected read path: ${candidate}`);
      }
      return VALID_ARTIFACT;
    },
    writeError: (diagnostic: string) => diagnostics.push(diagnostic),
  });
  return { dependencies, diagnostics, events, file, directory };
}

/**
 * Import one real authority CLI without substituting its validator.
 * @param file - Canonical or installed authority module path.
 * @returns The imported production authority module.
 */
async function authorityCli(file: string): Promise<AuthorityCliModule> {
  return import(pathToFileURL(file).href) as Promise<AuthorityCliModule>;
}

describe("materialized environment authority CLI binding", () => {
  it("does not invoke the authority CLI through envfile reverse export", () => {
    const envfileUrl = JSON.stringify(pathToFileURL(ENVFILE_MODULE).href);
    const program =
      `const loaded = await import(${envfileUrl});` +
      'if (typeof loaded.materializedOwnersMatch !== "function") {' +
      "process.exit(66);}" +
      'process.stdout.write("imported\\n");';
    const run = boundedSpawnSync({
      label: "the envfile authority reverse import",
      command: process.execPath,
      args: ["--input-type=module", "--eval", program],
      cwd: process.cwd(),
      env: { LANG: "C", LC_ALL: "C", PATH: "" },
    });

    expect(run.status).toBe(0);
    expect(run.stdout).toBe("imported\n");
    expect(run.stderr).toBe("");
  });

  it.each(LAYOUTS)(
    "imports $label authority when ambient argv1 cannot resolve",
    layout => {
      const missingArgv = path.resolve(
        "tests/helpers/__fixtures__/missing-authority-entrypoint.mjs"
      );
      const authorityUrl = JSON.stringify(pathToFileURL(layout.path).href);
      const program =
        `process.argv[1] = ${JSON.stringify(missingArgv)};` +
        `const loaded = await import(${authorityUrl});` +
        'if (typeof loaded.runMaterializedEnvAuthorityCli !== "function") {' +
        "process.exit(66);}" +
        'process.stdout.write("imported\\n");';

      expect(existsSync(missingArgv)).toBe(false);
      const run = boundedSpawnSync({
        label: `${layout.label} authority import with unresolved argv1`,
        command: process.execPath,
        args: ["--input-type=module", "--eval", program],
        cwd: process.cwd(),
        env: { LANG: "C", LC_ALL: "C", PATH: "" },
      });

      expect(run.status).toBe(0);
      expect(run.stdout).toBe("imported\n");
      expect(run.stderr).toBe("");
    }
  );

  it.each(LAYOUTS)(
    "uses immutable lstat/read/getuid facts in $label layout",
    async layout => {
      const observed = observation();
      const authority = await authorityCli(layout.path);

      const status = authority.runMaterializedEnvAuthorityCli(
        [VALUES_FILE],
        observed.dependencies
      );

      expect(status).toBe(0);
      expect(observed.diagnostics).toEqual([]);
      expect(observed.events).toHaveLength(4);
      const expected = [
        "getuid",
        `lstat:${VALUES_DIRECTORY}`,
        `lstat:${VALUES_FILE}`,
      ]
        .slice()
        .sort((left, right) => left.localeCompare(right));
      expect(
        observed.events
          .slice(0, 3)
          .slice()
          .sort((left, right) => left.localeCompare(right))
      ).toEqual(expected);
      expect(observed.events.at(-1)).toBe(`read:${VALUES_FILE}:utf8`);
    }
  );

  it.each(LAYOUTS)(
    "routes $label CLI ownership refusal through the real default validator",
    async layout => {
      const observed = observation(777);
      const authority = await authorityCli(layout.path);

      const status = authority.runMaterializedEnvAuthorityCli(
        [VALUES_FILE],
        observed.dependencies
      );

      expect(status).not.toBe(0);
      expect(observed.events).toHaveLength(3);
      const expected = [
        "getuid",
        `lstat:${VALUES_DIRECTORY}`,
        `lstat:${VALUES_FILE}`,
      ]
        .slice()
        .sort((left, right) => left.localeCompare(right));
      expect(
        observed.events.slice().sort((left, right) => left.localeCompare(right))
      ).toEqual(expected);
      expect(observed.diagnostics.join("\n")).toMatch(/ownership mismatch/iu);
      expect(observed.diagnostics.join("\n")).not.toContain(
        "value-never-printed"
      );
    }
  );

  it.each(LAYOUTS)(
    "invokes the $label exported default CLI driver exactly once as main",
    layout => {
      const source = readFileSync(layout.path, "utf8");

      expect(source).toMatch(
        /export function runMaterializedEnvAuthorityCli\s*\(/u
      );
      expect(
        source.match(/validateMaterializedEnvAuthority\(facts\)/gu)
      ).toHaveLength(1);
      expect(source).toMatch(
        /if\s*\(\s*invokedAsScript\(import\.meta\.url\)\s*\)/u
      );
      expect(source.match(EXECUTABLE_DRIVER_CALL)).toHaveLength(1);
      expect(
        source.match(/runMaterializedEnvAuthorityCli\s*\(/gu)
      ).toHaveLength(2);
    }
  );
});
