/**
 * Lisa must not name a downstream host project, and this is the check that
 * makes that binding rather than advisory.
 *
 * The rule lives in `.claude/rules/PROJECT_RULES.md` and `.agents/rules/`, but a
 * prose rule reaches only the agents that load it — Claude Code auto-loads
 * `.claude/rules/`, and every other agent reads host rules on demand, which an
 * agent writing a commit message has no reason to do. Measured 2026-08-17: 135
 * tracked files named a client and 48 files in the published tarball did, under
 * a convention everyone agreed with.
 *
 * A test runs in required CI for every agent and every human regardless of what
 * any of them loaded into context.
 * @module tests/unit/core/no-downstream-project-names
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  findDownstreamReferences,
  PLACEHOLDER_ACCOUNTS,
  PUBLIC_ORGS,
} from "../../../src/core/downstream-references.js";

const ROOT = process.cwd();

/**
 * Absolute git path, so the scan does not resolve a command off `PATH`.
 * Both are standard locations; the second covers Homebrew-first machines.
 */
const GIT = existsSync("/usr/bin/git")
  ? "/usr/bin/git"
  : "/opt/homebrew/bin/git";

/**
 * Files this check cannot usefully read.
 *
 * `CHANGELOG.md` is generated by semantic-release from commit history, so it
 * reproduces whatever the messages said; fixing it means fixing history, which
 * is a separate human-gated decision. Lockfiles and generated ledgers are
 * machine output whose contents are decided elsewhere.
 */
const EXEMPT = new Set([
  "CHANGELOG.md",
  "bun.lock",
  "package-lock.json",
  // This file. Its bite controls must contain examples of exactly what the
  // scan looks for, so scanning it would be self-refuting. Every example below
  // is synthetic for that reason — the exemption must not be able to hide a
  // real one.
  "tests/unit/core/no-downstream-project-names.test.ts",
]);

const EXEMPT_PREFIXES = ["dist/", "node_modules/", "coverage/"];

/**
 * Every tracked text file, as git sees it.
 * @returns Repo-relative paths.
 */
const trackedFiles = (): readonly string[] =>
  execFileSync(GIT, ["ls-files"], { cwd: ROOT, encoding: "utf-8" })
    .split("\n")
    .filter(Boolean)
    .filter(rel => !EXEMPT.has(rel))
    .filter(rel => !EXEMPT_PREFIXES.some(prefix => rel.startsWith(prefix)));

describe("Lisa never names a downstream project", () => {
  it("has no reference to a non-public org or a real AWS account id", () => {
    const violations: string[] = [];

    for (const rel of trackedFiles()) {
      const absolute = path.join(ROOT, rel);
      let contents: string;
      try {
        contents = fs.readFileSync(absolute, "utf-8");
      } catch {
        // Binary or unreadable: nothing to scan, and not a violation.
        continue;
      }
      for (const found of findDownstreamReferences(contents)) {
        violations.push(
          `${rel}:${found.line}  ${found.match} — ${found.reason}`
        );
      }
    }

    // The whole list, not a count: a reader fixing this needs the paths, and a
    // bare number would send them to re-run the scan themselves.
    expect(violations.join("\n")).toBe("");
  });

  it("flags a downstream reference and allows a public one", () => {
    // The bite control. Without it, a scan that silently matched nothing would
    // report the same clean result as a repository that is genuinely clean.
    expect(
      findDownstreamReferences("see https://github.com/SomeClient/frontend")
    ).toHaveLength(1);
    expect(
      findDownstreamReferences(
        "uses: SomeClient/frontend/.github/workflows/x.yml@main"
      )
    ).toHaveLength(1);
    expect(findDownstreamReferences("uses: actions/checkout@v6")).toHaveLength(
      0
    );
    expect(
      findDownstreamReferences(
        "see https://github.com/CodySwannGT/lisa/issues/1"
      )
    ).toHaveLength(0);
  });

  it("flags a real-looking AWS account id but not a placeholder", () => {
    expect(
      findDownstreamReferences("arn:aws:iam::987654321098:role/RemoteAgent")
    ).toHaveLength(1);
    expect(
      findDownstreamReferences("sso_account_id = 987654321098")
    ).toHaveLength(1);
    for (const account of PLACEHOLDER_ACCOUNTS) {
      expect(
        findDownstreamReferences(`arn:aws:iam::${account}:role/Example`)
      ).toHaveLength(0);
    }
  });

  it("keeps the org allowlist lowercase so matching cannot depend on case", () => {
    // `github.com/Actions/checkout` and `github.com/actions/checkout` are the
    // same org. Comparing lowercased input against a mixed-case list would let
    // one spelling through and refuse the other.
    for (const org of PUBLIC_ORGS) {
      expect(org).toBe(org.toLowerCase());
    }
  });
});
