/**
 * Lisa must not name a downstream host project, and this is the check that
 * makes that binding rather than advisory.
 *
 * The rule lives in `.claude/rules/PROJECT_RULES.md` and `.agents/rules/`, but a
 * prose rule reaches only the agents that load it — Claude Code auto-loads
 * `.claude/rules/`, and every other agent reads host rules on demand, which an
 * agent writing a commit message has no reason to do. Measured 2026-08-17: 135
 * tracked files named a client and 48 files in the published tarball did, under
 * a convention everyone agreed with.
 *
 * A test runs in required CI for every agent and every human regardless of what
 * any of them loaded into context.
 * @module tests/unit/core/no-downstream-project-names
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import type { NameMatcher } from "../../../src/core/downstream-names.js";
import {
  HOST_NAME_ENTRIES,
  hostNameEntries,
  MIN_NAME_LENGTH,
  NAME_ENV_VAR,
  nameEntry,
} from "../../../src/core/downstream-names.js";
import {
  findDownstreamReferences,
  PLACEHOLDER_ACCOUNTS,
  PUBLIC_ORGS,
} from "../../../src/core/downstream-references.js";

const ROOT = process.cwd();

/**
 * Absolute git path, so the scan does not resolve a command off `PATH`.
 * Both are standard locations; the second covers Homebrew-first machines.
 */
const GIT = existsSync("/usr/bin/git")
  ? "/usr/bin/git"
  : "/opt/homebrew/bin/git";

/**
 * Files this check cannot usefully read.
 *
 * `CHANGELOG.md` is generated by semantic-release from commit history, so it
 * reproduces whatever the messages said; fixing it means fixing history, which
 * is a separate human-gated decision. Lockfiles and generated ledgers are
 * machine output whose contents are decided elsewhere.
 */
const EXEMPT = new Set([
  "CHANGELOG.md",
  "bun.lock",
  "package-lock.json",
  // This file. Its bite controls must contain examples of exactly what the
  // scan looks for, so scanning it would be self-refuting. Every example below
  // is synthetic for that reason — the exemption must not be able to hide a
  // real one.
  "tests/unit/core/no-downstream-project-names.test.ts",
]);

const EXEMPT_PREFIXES = ["dist/", "node_modules/", "coverage/"];

/**
 * Every tracked text file, as git sees it.
 * @returns Repo-relative paths.
 */
const trackedFiles = (): readonly string[] =>
  execFileSync(GIT, ["ls-files"], { cwd: ROOT, encoding: "utf-8" })
    .split("\n")
    .filter(Boolean)
    .filter(rel => !EXEMPT.has(rel))
    .filter(rel => !EXEMPT_PREFIXES.some(prefix => rel.startsWith(prefix)));

describe("Lisa never names a downstream project", () => {
  it("has no reference to a non-public org or a real AWS account id", () => {
    const violations: string[] = [];

    for (const rel of trackedFiles()) {
      const absolute = path.join(ROOT, rel);
      let contents: string;
      try {
        contents = fs.readFileSync(absolute, "utf-8");
      } catch {
        // Binary or unreadable: nothing to scan, and not a violation.
        continue;
      }
      for (const found of findDownstreamReferences(contents)) {
        violations.push(
          `${rel}:${found.line}  ${found.match} — ${found.reason}`
        );
      }
    }

    // The whole list, not a count: a reader fixing this needs the paths, and a
    // bare number would send them to re-run the scan themselves.
    expect(violations.join("\n")).toBe("");
  });

  it("flags a downstream reference and allows a public one", () => {
    // The bite control. Without it, a scan that silently matched nothing would
    // report the same clean result as a repository that is genuinely clean.
    expect(
      findDownstreamReferences("see https://github.com/SomeClient/frontend")
    ).toHaveLength(1);
    expect(
      findDownstreamReferences(
        "uses: SomeClient/frontend/.github/workflows/x.yml@main"
      )
    ).toHaveLength(1);
    expect(findDownstreamReferences("uses: actions/checkout@v6")).toHaveLength(
      0
    );
    expect(
      findDownstreamReferences(
        "see https://github.com/CodySwannGT/lisa/issues/1"
      )
    ).toHaveLength(0);
  });

  it("flags a real-looking AWS account id but not a placeholder", () => {
    expect(
      findDownstreamReferences("arn:aws:iam::987654321098:role/RemoteAgent")
    ).toHaveLength(1);
    expect(
      findDownstreamReferences("sso_account_id = 987654321098")
    ).toHaveLength(1);
    for (const account of PLACEHOLDER_ACCOUNTS) {
      expect(
        findDownstreamReferences(`arn:aws:iam::${account}:role/Example`)
      ).toHaveLength(0);
    }
  });

  it("keeps the org allowlist lowercase so matching cannot depend on case", () => {
    // `github.com/Actions/checkout` and `github.com/actions/checkout` are the
    // same org. Comparing lowercased input against a mixed-case list would let
    // one spelling through and refuse the other.
    for (const org of PUBLIC_ORGS) {
      expect(org).toBe(org.toLowerCase());
    }
  });
});

/**
 * A matcher built from names that belong to nobody.
 *
 * Every example below is invented. The committed list is proved separately, by
 * its shape and by the scan above — a test that spelled a real name out to
 * prove the guard catches real names would be the leak the guard exists to
 * prevent.
 * @returns A matcher over the synthetic names.
 */
const syntheticMatcher = (): NameMatcher =>
  hostNameEntries({ [NAME_ENV_VAR]: "somehost, Widget Foundry" });

describe("the known-name check reaches the shape the regex cannot", () => {
  it("flags a bare host name in running prose", () => {
    // The measurement that made this necessary: the shape guard reported zero
    // violations on a tree that had 189, and every one of them looked like
    // this — a name in a sentence, with no `github.com` in front of it.
    const found = findDownstreamReferences(
      "Measured against somehost last week.",
      syntheticMatcher()
    );
    expect(found).toHaveLength(1);
    expect(found[0]?.match).toBe("somehost");
  });

  it("flags a bare host name in a code comment and in a local path", () => {
    expect(
      findDownstreamReferences(
        "// Evidence: somehost-backend pinned its tsconfig include.",
        syntheticMatcher()
      )
    ).toHaveLength(1);
    expect(
      findDownstreamReferences(
        "/Users/someone/workspace/somehost/infrastructure",
        syntheticMatcher()
      )
    ).toHaveLength(1);
  });

  it("flags a host name spelled with a separator or a different case", () => {
    for (const spelling of [
      "SomeHost",
      "SOMEHOST",
      "Widget Foundry",
      "widget-foundry",
      "widget_foundry",
      "WidgetFoundry",
    ]) {
      expect(
        findDownstreamReferences(
          `see ${spelling} for context`,
          syntheticMatcher()
        )
      ).toHaveLength(1);
    }
  });

  it("does NOT fire on file paths, date fractions or option syntax", () => {
    // This control is the whole reason the shape guard refused to match bare
    // `a/b` in prose, and it is the property a known list buys outright: none
    // of these tokens is a name, so none of them can hash to one. A guard that
    // fired here would be switched off within a day, and a switched-off guard
    // catches nothing at all.
    for (const line of [
      "import { x } from '../../src/core/index.js';",
      "see src/core/downstream-references.ts:42 for the reason",
      "Measured 2026/08/20, and again on 08/20/2026",
      "roughly 3/4 of the tracked files",
      "run with --exclude=a/b and -o n/a",
      "docs/decisions/2026-08-19-guard-mutation-gate.md",
      "uses: actions/checkout@v6",
      "https://github.com/CodySwannGT/lisa/issues/1",
    ]) {
      expect(findDownstreamReferences(line, syntheticMatcher())).toEqual([]);
    }
  });

  it("does NOT fire on a longer word that merely starts with a name", () => {
    // Boundary anchoring at both ends. Without the trailing boundary, an entry
    // would fire inside every word it happens to prefix, which is the
    // false-positive class that gets a guard disabled.
    for (const line of [
      "somehosting is a different word",
      "the somehostile takeover",
      "presomehost and somehostx",
    ]) {
      expect(findDownstreamReferences(line, syntheticMatcher())).toEqual([]);
    }
  });

  it("does NOT join two words across a sentence boundary", () => {
    // `". "` is two characters, so it cannot glue `widget` to `Foundry`. One
    // separator may; a sentence may not.
    expect(
      findDownstreamReferences(
        "shipped the widget. Foundry work lands next.",
        syntheticMatcher()
      )
    ).toEqual([]);
    expect(
      findDownstreamReferences(
        "the widget, foundry, and mill teams",
        syntheticMatcher()
      )
    ).toEqual([]);
  });

  it("refuses an environment name too short to be safe", () => {
    // A three-character entry matches an initialism in almost any repository.
    // Accepting one would hand back the false-positive problem a known list
    // exists to avoid.
    const short = hostNameEntries({ [NAME_ENV_VAR]: "abc" });
    expect(short.entries.size).toBe(HOST_NAME_ENTRIES.length);
    expect(MIN_NAME_LENGTH).toBeGreaterThan(3);
  });

  it("keeps the committed list armed and stored as digests, not names", () => {
    // Two claims, both load-bearing. Armed: an empty list is a guard that
    // reports a clean tree for the same reason a broken one does. Digests: a
    // plaintext list in a public repository publishes what it protects.
    expect(HOST_NAME_ENTRIES.length).toBeGreaterThan(0);
    for (const entry of HOST_NAME_ENTRIES) {
      expect(entry).toMatch(/^\d+:[0-9a-f]{10}$/u);
      expect(Number(entry.split(":")[0])).toBeGreaterThanOrEqual(
        MIN_NAME_LENGTH
      );
    }
  });

  it("treats case and separators as spelling rather than identity", () => {
    expect(nameEntry("Some-Host")).toBe(nameEntry("some host"));
    expect(nameEntry("SomeHost")).toBe(nameEntry("somehost"));
    expect(nameEntry("somehost")).not.toBe(nameEntry("somehosts"));
  });
});
