/**
 * Python/Poetry coverage for the dependencies/supply-chain readiness producer
 * (B5, PRD #1739, #1896).
 * @module tests/unit/cli/doctor-readiness-supply-chain-python
 */
import { rm } from "node:fs/promises";
import { afterEach, describe, expect, it } from "vitest";
import { assessReadiness } from "../../../src/cli/doctor-readiness-blockers.js";
import { assessDependenciesSupplyChainDimension } from "../../../src/cli/doctor-readiness-supply-chain.js";
import {
  asFindings,
  makeScratchRepo,
  SKIP,
  writeRepoFile,
} from "../../helpers/readiness-workflow-fixtures.js";

/** The ship blocker this producer can stand up. */
const BLOCKER_ID = "B5";

/** The Python manifest B5 reads when no package.json exists. */
const PYPROJECT = "pyproject.toml";

/** The Poetry lockfile B5 requires for repeatable installs. */
const POETRY_LOCK = "poetry.lock";

/** The update-bot config path used as a Python dependency-audit gate. */
const DEPENDABOT_PATH = ".github/dependabot.yml";

/** Shared Poetry package metadata used by pyproject fixtures. */
const POETRY_PROJECT_HEADER = [
  "[tool.poetry]",
  'name = "scratch"',
  'version = "0.1.0"',
];

/** Shared Python runtime constraint used by Poetry fixtures. */
const POETRY_PYTHON_RUNTIME = 'python = "^3.11"';

/** Poetry dependency table header used by pyproject fixtures. */
const POETRY_DEPENDENCIES_TABLE = "[tool.poetry.dependencies]";

/** Minimal Poetry manifest with one constrained dependency. */
const CONSTRAINED_PYPROJECT = [
  ...POETRY_PROJECT_HEADER,
  POETRY_DEPENDENCIES_TABLE,
  POETRY_PYTHON_RUNTIME,
  'requests = "^2.32.0"',
  "",
].join("\n");

/** Minimal Poetry lockfile body used by fixture repositories. */
const MINIMAL_POETRY_LOCK =
  "# This file is automatically @generated by Poetry.\n";

/** Evidence text emitted when no Python dependency-audit gate is present. */
const PYTHON_AUDIT_GATE_EVIDENCE = "Python dependency-audit gate";

/** A dependabot config that watches Python dependencies. */
const PYTHON_DEPENDABOT_YML = [
  "version: 2",
  "updates:",
  "  - package-ecosystem: pip",
  '    directory: "/"',
  "    schedule:",
  "      interval: weekly",
  "",
].join("\n");

let tempDir: string | undefined;

/**
 * Resolve a scratch repository for one test case.
 * @returns Temporary directory path
 */
async function getTempDir(): Promise<string> {
  tempDir ??= await makeScratchRepo("supply-chain-python");
  return tempDir;
}

afterEach(async () => {
  if (tempDir) {
    await rm(tempDir, { force: true, recursive: true });
    tempDir = undefined;
  }
});

describe("assessDependenciesSupplyChainDimension — Python/Poetry repositories", () => {
  it("FAILs with B5 instead of SKIP when pyproject lacks Poetry confidence evidence", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(
      cwd,
      PYPROJECT,
      [
        POETRY_DEPENDENCIES_TABLE,
        POETRY_PYTHON_RUNTIME,
        'requests = "*"',
        "",
      ].join("\n")
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe("FAIL");
    const finding = asFindings(record.findings).find(
      candidate => candidate.blocker === BLOCKER_ID
    );
    expect(finding?.evidence).toContain(POETRY_LOCK);
    expect(finding?.evidence).toContain(PYTHON_AUDIT_GATE_EVIDENCE);
    expect(finding?.evidence).toContain("requests");
    expect(assessReadiness([record]).blockers[0].id).toBe(BLOCKER_ID);
  });

  it("PASSes a locked and audited Poetry repository with constrained deps", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(cwd, PYPROJECT, CONSTRAINED_PYPROJECT);
    await writeRepoFile(cwd, POETRY_LOCK, MINIMAL_POETRY_LOCK);
    await writeRepoFile(cwd, DEPENDABOT_PATH, PYTHON_DEPENDABOT_YML);

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe("PASS");
    expect(assessReadiness([record]).blockers).toEqual([]);
    const findings = asFindings(record.findings);
    expect(findings[0].evidence).toContain(PYPROJECT);
    expect(findings[0].evidence).toContain(POETRY_LOCK);
    for (const finding of findings) {
      expect(Object.hasOwn(finding, "blocker")).toBe(false);
    }
  });

  it("SKIPs with an explicit reason for non-Poetry pyproject files", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(
      cwd,
      PYPROJECT,
      [
        "[project]",
        'name = "scratch"',
        "dependencies = [",
        '  "requests>=2.32.0",',
        "]",
        "",
      ].join("\n")
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe(SKIP);
    const findings = asFindings(record.findings);
    expect(findings[0].reason).toContain("Poetry dependency tables");
    expect(assessReadiness([record]).blockers).toEqual([]);
  });

  it("SKIPs with an explicit reason when Poetry tables contain no dependency specs", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(
      cwd,
      PYPROJECT,
      [
        ...POETRY_PROJECT_HEADER,
        POETRY_DEPENDENCIES_TABLE,
        POETRY_PYTHON_RUNTIME,
        "",
      ].join("\n")
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe(SKIP);
    const findings = asFindings(record.findings);
    expect(findings[0].reason).toContain("declares no Poetry dependencies");
    expect(assessReadiness([record]).blockers).toEqual([]);
  });

  it("SKIPs with an explicit reason when pyproject TOML cannot be parsed", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(
      cwd,
      PYPROJECT,
      [
        POETRY_DEPENDENCIES_TABLE,
        POETRY_PYTHON_RUNTIME,
        'requests = "',
        "",
      ].join("\n")
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe(SKIP);
    const findings = asFindings(record.findings);
    expect(findings[0].reason).toContain("could not be parsed");
    expect(findings[0].reason).toContain("Python dependency specs");
    expect(assessReadiness([record]).blockers).toEqual([]);
  });

  it("does not accept commented Python audit mentions as audit gates", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(cwd, PYPROJECT, CONSTRAINED_PYPROJECT);
    await writeRepoFile(cwd, POETRY_LOCK, MINIMAL_POETRY_LOCK);
    await writeRepoFile(
      cwd,
      ".github/workflows/quality.yml",
      "jobs:\n  test:\n    steps:\n      # - run: pip-audit\n"
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe("FAIL");
    const finding = asFindings(record.findings).find(
      candidate => candidate.blocker === BLOCKER_ID
    );
    expect(finding?.evidence).toContain(PYTHON_AUDIT_GATE_EVIDENCE);
  });

  it("accepts Safety CLI 3 scan commands as Python audit gates", async () => {
    const cwd = await getTempDir();
    await writeRepoFile(cwd, PYPROJECT, CONSTRAINED_PYPROJECT);
    await writeRepoFile(cwd, POETRY_LOCK, MINIMAL_POETRY_LOCK);
    await writeRepoFile(
      cwd,
      ".github/workflows/quality.yml",
      "jobs:\n  audit:\n    steps:\n      - run: safety scan\n"
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe("PASS");
    expect(assessReadiness([record]).blockers).toEqual([]);
  });

  it("bounds Python B5 evidence when many dependencies violate the confidence model", async () => {
    const cwd = await getTempDir();
    const deps = Array.from({ length: 14 }, (_, index) => `dep${index} = "*"`);
    await writeRepoFile(
      cwd,
      PYPROJECT,
      [POETRY_DEPENDENCIES_TABLE, POETRY_PYTHON_RUNTIME, ...deps, ""].join("\n")
    );

    const record = await assessDependenciesSupplyChainDimension(cwd);

    expect(record.status).toBe("FAIL");
    const finding = asFindings(record.findings).find(
      candidate => candidate.blocker === BLOCKER_ID
    );
    expect(finding?.evidence).toContain("+4 further finding(s)");
    expect(finding?.evidence).not.toContain("dep12");
    expect(finding?.evidence).not.toContain("dep13");
  });
});
