/**
 * Project paths that `lisa apply` GENERATES rather than copies.
 * @module migrations/generated-paths
 */

/**
 * Repo-relative prefixes that apply regenerates on every run.
 *
 * A generated path fails differently from a `copy-overwrite` template, and the
 * difference decides what a guard should tell someone who edits one:
 *
 * - **`copy-overwrite`, host-edited** — apply PRESERVES it. The file silently
 *   forks and stops receiving upstream fixes while looking current. Measured:
 *   four mutated files, `Overwritten: 0`.
 * - **generated** — apply REBUILDS it. The edit works locally, CI agrees, and
 *   the next `bun install` reverts it with nothing reporting that it had.
 *
 * So this list exists to let one guard give two accurate answers, rather than
 * one answer that is wrong for half the files it covers.
 *
 * It is the SINGLE source: the migration that vendors a tree imports its prefix
 * from here, and the hook reads this module out of the installed package. A
 * hook carrying its own copy of the list would be the defect this repository
 * has filed repeatedly — a second place to update that nobody updates, which
 * then governs silently.
 */
export const GENERATED_PATH_PREFIXES: readonly string[] = [".lisa/lisa-oxlint"];

/**
 * Whether a repo-relative path is regenerated by apply.
 * @param relativePath - Repo-relative destination path
 * @returns True when apply rebuilds this path rather than copying it
 */
export function isGeneratedPath(relativePath: string): boolean {
  const normalised = relativePath.replaceAll("\\", "/").replace(/^\.\//u, "");
  return GENERATED_PATH_PREFIXES.some(
    prefix => normalised === prefix || normalised.startsWith(`${prefix}/`)
  );
}
