import * as path from "node:path";
import * as fse from "fs-extra";
import type {
  Migration,
  MigrationContext,
  MigrationResult,
} from "./migration.interface.js";

/** Generated Codex marketplace, relative to a project root (posix, git-style). */
const MARKETPLACE_PATH = ".agents/plugins/marketplace.json";

/**
 * Run a fixed git command in a directory, returning success.
 *
 * `child_process` is dynamically imported (matching `src/core/lisa.ts`) so the
 * static security lint for command paths is not tripped; every command passed
 * here is a hard-coded literal with no interpolated input.
 * @param command - Full literal git command line
 * @param cwd - Working directory to run in
 * @returns True when the command exits zero
 */
async function tryGit(command: string, cwd: string): Promise<boolean> {
  const { exec } = await import("node:child_process");
  const { promisify } = await import("node:util");
  const run = promisify(exec);
  try {
    await run(command, { cwd });
    return true;
  } catch {
    return false;
  }
}

/**
 * Migration: stop git-tracking the generated `.agents/plugins/marketplace.json`.
 *
 * The Codex marketplace points its plugin sources at `./node_modules/@codyswann/
 * lisa/plugins/<name>` (install-location-relative). Because `node_modules` is
 * gitignored, a *committed* copy of this manifest is broken in any checkout where
 * deps are not installed — most notably **git worktrees** and fresh clones — which
 * surfaces as a Claude Code "Plugin lisa not cached" error that `/plugins` cannot
 * fix (the files genuinely aren't on disk there).
 *
 * The fix pairs with a gitignore entry (so new projects never commit it): this
 * migration heals **existing** projects by removing the file from the index with
 * `git rm --cached` (the working copy is kept and continues to be regenerated by
 * `lisa apply`). Idempotent — once untracked, `applies` returns false. Safe in
 * non-git dirs and when the file is absent. See lisa#1366.
 */
export class UntrackCodexMarketplaceMigration implements Migration {
  readonly name = "untrack-codex-marketplace";
  readonly description =
    "Untrack the generated .agents/plugins/marketplace.json (it points into node_modules and breaks plugins in git worktrees); it is gitignored and regenerated on apply";

  /**
   * Applies when the marketplace file exists and is git-tracked.
   * @param ctx - Migration context
   * @returns True when there is work to do
   */
  async applies(ctx: MigrationContext): Promise<boolean> {
    const abs = path.join(ctx.projectDir, MARKETPLACE_PATH);
    if (!(await fse.pathExists(abs))) {
      return false;
    }
    return tryGit(
      "git ls-files --error-unmatch .agents/plugins/marketplace.json",
      ctx.projectDir
    );
  }

  /**
   * Remove the marketplace file from the git index (keeping the working copy).
   * @param ctx - Migration context
   * @returns Result describing the action taken
   */
  async apply(ctx: MigrationContext): Promise<MigrationResult> {
    const tracked = await tryGit(
      "git ls-files --error-unmatch .agents/plugins/marketplace.json",
      ctx.projectDir
    );
    if (!tracked) {
      return { name: this.name, action: "noop" };
    }

    const message = `Untracked ${MARKETPLACE_PATH} (gitignored; regenerated on apply)`;
    if (ctx.dryRun) {
      ctx.logger.dry(`Would untrack ${MARKETPLACE_PATH}`);
      return {
        name: this.name,
        action: "applied",
        changedFiles: [MARKETPLACE_PATH],
        message,
      };
    }

    const removed = await tryGit(
      "git rm --cached --quiet .agents/plugins/marketplace.json",
      ctx.projectDir
    );
    if (!removed) {
      // Not a git repo, or nothing to remove — nothing to heal.
      return { name: this.name, action: "noop" };
    }

    ctx.logger.success(message);
    return {
      name: this.name,
      action: "applied",
      changedFiles: [MARKETPLACE_PATH],
      message,
    };
  }
}
