/** Generated by scripts/generate-lisa-owned-hash-ledger.mjs. Do not edit. */

/**
 * Every content hash Lisa has published at each Lisa-owned destination path.
 *
 * A host copy whose hash appears here is provably an older Lisa artifact and may
 * be refreshed. One that appears nowhere here was edited downstream, and refresh
 * refuses rather than risk deleting a stronger guard. See
 * `src/core/lisa-owned-provenance.ts`.
 */
export const LISA_OWNED_HASH_LEDGER: Readonly<
  Record<string, readonly string[]>
> = Object.freeze({
  "scripts/lisa-clean-git-env.sh": Object.freeze([
    "d15af6f13eedbca41046070972380e69fc0af8f7d903aac12b8644389b9a0c91",
    "e7121a0ee9e1bf7c01cd2ab55f563dd6d9ab75990739bb6ddf571a513efa10e9",
  ]),
  "scripts/lisa-command-envelope.mjs": Object.freeze([
    "2011331056b1c86bd181649713a395dbfd2768f9fcd7e37b521d6ad2a9318ea9",
    "4f76bb7d466eb153a4e1414d06f12856a1242de2cfa4cb4b1b942cf29d8b7f37",
    "6b198f088cd3cd862d4357fbb069b1ad5d3afeb7be594f2bf1ff603b092a8354",
    "e06cb11f1418fe94564cea527a22b039f53b7ab10c1cd182264a31e52bba9fa8",
  ]),
  "scripts/lisa-destructive-guard.mjs": Object.freeze([
    "4fb431a3c58f443e303d613934d023d9e95ddae5c42710bb7009f7c080c82a64",
  ]),
  "scripts/lisa-enforcement-fallback.sh": Object.freeze([
    "1bec5f3c284b3febdc471487ee6a23ffb72bd4e7b293f9e26b0188f32318c722",
    "3049c2f1051c7c02dd60b62355964651e1565ebe6bdcb5e37634cd686cf1deb1",
    "8dc942ac4edc2017d6b8277296c8f80542e7c024eef1bb65de609979d0ca9a0e",
    "9cab71562d01421d57c6719318a4d03a6249a45c1aea434db3ff26e3065eeb66",
    "d7d88e44763694bed5eae998cd3663922c957e49f9f9621d9201f0417a4128ad",
    "e17c45f7cadf0fb55dd07270776caf211af99b7d4771a4fde75aafe5919e8dbe",
  ]),
  "scripts/lisa-floor-collisions.mjs": Object.freeze([
    "2d11968f6852ab745cba939de03c6d6cb5f413975d2cfc8fc447bdd0b218e91a",
    "3c7a0234b4f5609fce49e44711d2ec86af8cf7fb82b0831e4450e3347ecefe45",
    "a612f172282d13ba9318fe5e03689d7c6ff42a0122d0c9d5d39051e1967b93dc",
  ]),
  "scripts/lisa-hooks/block-direct-issue-create.sh": Object.freeze([
    "22184f1dd1b96e818741bd4ae659446299535d7ce594817155edebac4172a7ba",
    "60a4f94ec671b2372f7492680ab327d97aff686588ce85791f54e0fbd098b0ca",
    "73e94b73830d8961026947d99bf4ac5f959b5bca025203b913d8a6363cbe2b9f",
    "847dfca48823a495fc3de47dfdb4b26e49d6808c6570c46d024a99793df1d370",
  ]),
  "scripts/lisa-hooks/block-instruction-file-edits.sh": Object.freeze([
    "6f52076e3488821d638b6dd45b5faca527d92b181cc12e6e5033859e0786c8a7",
    "850cfc23852eb752114ae1e938a1c7bcf34bc50c85d3aaca0c02311cc8c0ef70",
    "8996e0bcbf1db085a5d99734e797c91f5025997bd967bc374efff8348dac14c2",
    "be1e77fb0ddb246eddae71ebac25e972c3c9e8079514e0dc78d0b73df919464c",
    "d47314b66d6ce85f77d6e058f861eede4462b2b0a33d54e82ff1c931167ec3f7",
  ]),
  "scripts/lisa-hooks/block-no-verify.sh": Object.freeze([
    "031ef7a53fc49cb18665105b834b7b50ad6a43317e0821949809e877e0562ce4",
    "18b7bb8867c5e6f719a9c503a38525f4c05e3d611717c3e1a503cf58dfb2832f",
    "2df476aacebcb2544a12f459a0092e88eb28c0d00e45fd7ed909c75dfe441027",
    "33e2bd341eb992036059b0c4606db35a218adcfeca7e44d174fedf8ebdff29d2",
    "3b93a0affab6413e3c14a6f43de5acb586286ed1819ece0a66b30429b4d00490",
    "3ff7255f395a9552366faaac34d383f4c95fecfb39882cd1d57854356422fe61",
    "7790a560850c9d38709dbaccdaa10733e632c1bd4d975cbec7e3cc5a8650b36a",
    "a6ed91576efebb6ba40cfa4e9d8a3e8566314909210ae8d5860be62a3feb4cff",
    "aa95a84f9f9224914947a09b858535aa8bd052199ff64cb53768cf78fb69b687",
    "b9f299cb9d3ad75b71296376ae2c40eb207a3b2706dafdaa41fc586050a53aad",
    "dd1aea1b9fdd0da023bf704b331b350bc14620f4364afa5001c6690fcbc940cc",
    "e3407d63eae16662923d46b75b6a41e7ca7ab206b428ea2cbb0b4fee226f6516",
  ]),
  "scripts/lisa-hooks/block-shell-json-parsing.sh": Object.freeze([
    "1934a15e154fda3c2a40979a5cd6225661b14fe7bc77328a69ce499bea85dba7",
    "3b5f074f3ab5708030af507eea962389f3b067c5dbdc76580bd9e44d3ac6c603",
    "90601e31603c440d8f19d213d63bfef8d18596c60f88cb6e28c93d12453c5c0c",
  ]),
  "scripts/lisa-hooks/parity-safety-net.sh": Object.freeze([
    "062c69eea85157f1e941ec3626d8912aa9f182af6ccdbe19687588a6074db5ce",
    "07002535de10d89f6d73e8922517550a02a8974549aaf200c9c314e6f4f83c70",
    "1162ffd16cef3b23282d2f5207abcb88429462a74a9df1035f0df4968f6dd456",
    "14fc5e292aebf83dd24fec12fb32e2beb509a9324f127a24a64d5c5d4d05c576",
    "1bf3512bb94923a6cb25b1e7a619a3fc8e1336bffa16f499b459aaee3eaed66d",
    "388cf8847581d96a1ff8ea98290a33a5f96d67cdd502ea807a0b8d88efe90e19",
    "64546813f168fb446f39e34bc674fd3af85b15bd5e7f4f6bf4503463e701a7b9",
    "772202ddd42d626625ff719666afbbe83445d8bae1bc7c0fb5ffdcb402be83f8",
    "7f55986eb29f8ace8616595da4bbe60d80a96f9f29b24fb72efd66bb96b22464",
    "8e19d5f1ba7abe3d22fbee47ff8e0fad76b965ccca20b8849e3c43ab07d9a4ef",
    "a22fd1b7c483f1a538202353ee85c82be17a8910e03c0a930635ce8cb3595c64",
    "b83c5043a0f29b2d8851258acfe6906aab7922cd80f486e25220e55f26a8c0a5",
    "caea02a07027fc1c74d47e08b36299d369c5c9f7c4043da8828fbca3c64eb2aa",
    "d12583803e8ff5e4b64e68eafc8d3c377af4c400d8b7ecd1c7fe699d8f92784a",
    "d9ea58150aa27e7f0aa9a4ef155ed446d30bdfc932d01c64e2b8ca211aa0de7b",
    "f740f600b255742a50f28e5c9d09427c5783c4084e84052dca46bc1f0c94a187",
    "fa8f4a6517eacd9266feb7afd62398cdf2075d4824cac24b45bb64ad0cd18c86",
  ]),
  "scripts/lisa-hooks/sonar-secrets.sh": Object.freeze([
    "7a408788975a6351d53e14aa32bb9a5d161f33df9dfea59ba32784ae33a62e67",
    "945453fb275a58aa7185e150e6b05e5810739750928ab5bd6edfbf87d1c8aa0d",
    "bf4132e49ba18e2f7e941520c299c15aeeacfd220e489f3d2eb8397f2048157b",
  ]),
  "scripts/lisa-mutation.mjs": Object.freeze([
    "7d8d24dea151ef2178807046e97aea7ebfadd9c88eb50347feb7bb4bb190227d",
    "8e0bdb491dfaea04e88be1c1e2c6cc7cd34fa4ca18adddf5fecc43d7de8ffded",
    "a630bde6cddae283776b8d34763a3642edbea8096d583a90ec6d43a9588ca8a6",
  ]),
  "scripts/lisa-schema-validate.mjs": Object.freeze([
    "2ace82daacdebbbb00a7eceb09fbe82cabec04330a083ca10417b2ee4e0a63eb",
    "4a05a0ed70a274827fd2f0fd0c98890c66bee2fde70785b8379943ebe6650473",
    "9dd145c0f9dac6ed252b13d32e130dbab964da6cd357981b58541780ecb2f981",
  ]),
  "scripts/lisa-work-item.mjs": Object.freeze([
    "238dc2da29938edd92518c2b08192d14c6f2751ed175c07d6e882814829b7b7e",
    "2d9ca0841db9e75ddfd95e3a4d485fd01aa639a512ef648996f565b7991d8e2b",
    "4c263fef48c03b3b6c623ea8a6cd55505bfaf28197e5072226ea35f9f3d26885",
    "5eb31c284e820a51312d4484f0669128007326af55ee515923fec33700d003a1",
    "6a8be8577242588f14ab52b25b2a22b6def53aefa9513b4d3d7c49f4d8027079",
    "9223856be4618fb1e3e731b259ae5bf5328decc322f0b4a0d0fd18d6b12cd45a",
    "96a87c131606b3edd43e52485e68f8ffbf5c528cb4beb7a1185263519a9632ce",
    "ab0dede91c5c8a07984ae13aa48ec70cdcd2fa691b59617bc4b57998dc79a51c",
    "c78df9d5f0f3fc388ff60a7db5898478a2a4d6d7325833f10384b5a8c62bb34a",
    "e30016a49deff1c3cd3ae7951262aeb2ef3d472bce76bbbe2a177db6017c7cad",
    "e41e9534988ce69a836664437a78f3a3f3dc7ebbe396c86cdab0ea63fb7c19da",
    "f12006df4ed9974f65d955718af7dcc8a079799d02c58bd38b2d9c49f271db72",
    "f88f69d44693084428f44e3f2b80afecda08c7ee8747588f40277fdc9396fd8f",
    "fc0d92739e620d8fd70f7aa4a12d3e0b3a8f790d47c4a8322040f32c30b9445a",
    "fe064a2bd11200ed256fb36e203978f858fccbcaf40708496c066383345900ef",
  ]),
  "scripts/schemas/lisa-command-envelope.v1.schema.json": Object.freeze([
    "d153b7c2953a30f180e38f09e98240c63327f5196eeba9bdf545e5a1f125a879",
  ]),
  "scripts/schemas/lisa-state-contract.v1.schema.json": Object.freeze([
    "6b7afe4ffeba8aaa53871d8855172f7eacde05953b1321145218ec638ff5c1c4",
  ]),
});
