/**
 * @file nightly-e2e-guard-behavior-certificate.ts
 * @description Generated exact-byte certificates for behavior-proven Lisa guard artifacts
 * @module core/nightly-e2e-guard-behavior-certificate
 * Generated by scripts/generate-nightly-e2e-guard-certificate.mjs.
 */

/** Behavior-certificate schema consumed by doctor. */
export const NIGHTLY_E2E_GUARD_CERTIFICATE_SCHEMA_VERSION = 1;

/**
 * Exact digests whose real package handlers passed the bounded-waiver suite.
 * Generic Lisa ownership hashes are deliberately not consulted at runtime.
 */
export const NIGHTLY_E2E_GUARD_BEHAVIOR_CERTIFICATES = Object.freeze({
  "1c79ec49e5f4a3bba700bc1d97e9fc0f4f1799dec3acdf2bed5e3e5b866a0efd":
    Object.freeze({
      contractVersion: "1.1.0",
      packageVersions: Object.freeze(["2.352.0"]),
      provenances: Object.freeze([
        "git tag v2.353.0 package @codyswann/lisa@2.352.0 (typescript/copy-overwrite/scripts/check-nightly-e2e-health.mjs)",
      ]),
    }),
  "898ee0247806c7aa6e98328662d80bcff22ff067999298865462a58daef8bb22":
    Object.freeze({
      contractVersion: "1.8.0",
      packageVersions: Object.freeze(["4.26.1"]),
      provenances: Object.freeze([
        "git tag v4.26.1 package @codyswann/lisa@4.26.1 (typescript/copy-overwrite/scripts/check-nightly-e2e-health.mjs)",
      ]),
    }),
  "92a95288ee845ceb20342bbd52fc796d45bf5cd0afa513c058bf37e23985b9b8":
    Object.freeze({
      contractVersion: "1.7.0",
      packageVersions: Object.freeze(["4.17.15"]),
      provenances: Object.freeze([
        "git tag v4.17.16 package @codyswann/lisa@4.17.15 (typescript/copy-overwrite/scripts/check-nightly-e2e-health.mjs)",
      ]),
    }),
  dfd2fef680de5ef03e63075e8a61c62ca4d95cdfdff6201939b79c748d3397f6:
    Object.freeze({
      contractVersion: "1.9.0",
      packageVersions: Object.freeze(["4.45.4"]),
      provenances: Object.freeze([
        "workspace package @codyswann/lisa@4.45.4 (typescript/copy-overwrite/scripts/check-nightly-e2e-health.mjs)",
      ]),
    }),
});
