#!/usr/bin/env bash
# Fails if anything `build-plugins.sh` generates is out of sync with its source.
#
# That is two sets, and for a long time only the first was checked (#3064): the
# generated plugin directories under plugins/, and the files the same build
# materializes into the stack lanes and host guard directories WELL OUTSIDE
# plugins/. Both halves are checked here now, by the same mechanism.
#
# The plugins/ half. This guards against editing the
# build artifact directly: build-plugins.sh runs `rm -rf plugins/lisa && cp -r
# plugins/src/base`, so any artifact-only edit is silently discarded on the next
# build/release. Two real PRs (#471, #478) were wiped this way before this check
# existed.
#
# The check is a reproducibility test: regenerate the artifacts from source and
# assert the working tree is unchanged. A diff means either (a) someone edited
# plugins/lisa** directly instead of plugins/src**, or (b) someone edited
# plugins/src** but forgot to run `bun run build:plugins` and commit the result.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

if [ -n "$(git status --porcelain -- plugins/ 2>/dev/null)" ]; then
  echo "✗ plugins/ has uncommitted changes before the sync check could run." >&2
  echo "  Commit them, then re-run: bun run check:plugins" >&2
  echo "  (To set them aside instead, save a patch under your own TMPDIR — not" >&2
  echo "   the stash, which is one stack shared by every worktree of a clone.)" >&2
  exit 1
fi

# The same precaution for the generated files OUTSIDE plugins/, using the
# committed manifest — which the check above has just proved is the committed
# one, since it lives under plugins/.
#
# Without this, a directly-edited copy that was never committed is REVERTED by
# the rebuild below and the tree reads clean: the check would pass having
# silently discarded the edit, which is the precise failure the plugins/
# pre-check exists to prevent. Absent on a first run, before any manifest has
# been committed; the post-build check covers that case.
MATERIALIZED_MANIFEST="$ROOT_DIR/plugins/materialized-artifacts.json"
committed_manifest_paths=""
if [ -f "$MATERIALIZED_MANIFEST" ]; then
  committed_manifest_paths="$(jq -r '.[]' "$MATERIALIZED_MANIFEST" | LC_ALL=C sort)"
  committed_generated=()
  while IFS= read -r committed_path; do
    if [ -n "$committed_path" ]; then
      committed_generated+=("$committed_path")
    fi
  done < <(jq -r '.[]' "$MATERIALIZED_MANIFEST")
  if [ "${#committed_generated[@]}" -gt 0 ]; then
    pre_build_status="$(git status --porcelain -- "${committed_generated[@]}")"
    if [ -n "$pre_build_status" ]; then
      echo "✗ Generated files outside plugins/ have uncommitted changes before the sync check could run." >&2
      echo "" >&2
      printf "%s\n" "$pre_build_status" | sed 's/^/    /' >&2
      echo "" >&2
      echo "  These are generated by 'bun run build:plugins'. Rebuilding would" >&2
      echo "  overwrite them, so the check refuses rather than discarding an edit" >&2
      echo "  and reporting a clean tree. Edit the canonical source instead, or" >&2
      echo "  save a patch under your own TMPDIR — not the stash, which is one" >&2
      echo "  stack shared by every worktree of a clone — then re-run:" >&2
      echo "  bun run check:plugins" >&2
      exit 1
    fi
  fi
fi

bun run build:plugins >/dev/null

# Did the SET of destinations change? Asked before the plugins/ diff below,
# because the manifest lives under plugins/ and that diff would otherwise
# swallow this as a one-line "plugin artifacts out of sync" naming the manifest
# and nothing else — technically a refusal, but it tells you nothing about
# which destination appeared or vanished.
#
# This is the arm that makes an unexpectedly SMALL set fail. Every materialize
# call is guarded on its source and its generator being present, so a moved
# source does not error — it silently stops writing, and the copies it used to
# own become unowned files nothing checks. Comparing against the committed set
# names them.
if [ ! -f "$MATERIALIZED_MANIFEST" ]; then
  echo "✗ $MATERIALIZED_MANIFEST is missing after the build." >&2
  echo "  build-plugins.sh writes it on every successful run, so its absence" >&2
  echo "  means the build did not complete — not that there is nothing to check." >&2
  exit 1
fi
current_manifest_paths="$(jq -r '.[]' "$MATERIALIZED_MANIFEST" | LC_ALL=C sort)"
if [ "$current_manifest_paths" != "$committed_manifest_paths" ]; then
  echo "✗ The set of files this build generates outside plugins/ has changed." >&2
  echo "" >&2
  added="$(comm -13 <(printf "%s\n" "$committed_manifest_paths") <(printf "%s\n" "$current_manifest_paths"))"
  removed="$(comm -23 <(printf "%s\n" "$committed_manifest_paths") <(printf "%s\n" "$current_manifest_paths"))"
  if [ -n "$added" ]; then
    echo "  Now generated, and not recorded before:" >&2
    printf "%s\n" "$added" | sed 's/^/    /' >&2
    echo "" >&2
  fi
  if [ -n "$removed" ]; then
    echo "  Recorded before, and NO LONGER generated:" >&2
    printf "%s\n" "$removed" | sed 's/^/    /' >&2
    echo "" >&2
    echo "  A destination that stops being generated is the dangerous half: the" >&2
    echo "  file stays in the tree, still shipped, and nothing regenerates or" >&2
    echo "  checks it. Confirm the materialize call was removed deliberately —" >&2
    echo "  and if it was, delete the copies it used to own." >&2
    echo "" >&2
  fi
  echo "  plugins/materialized-artifacts.json is written by 'bun run" >&2
  echo "  build:plugins' and records what that run actually wrote. Commit it" >&2
  echo "  together with the destinations above." >&2
  exit 1
fi

plugin_status="$(git status --porcelain -- plugins/)"
if [ -n "$plugin_status" ]; then
  echo "✗ Generated plugin artifacts are out of sync with plugins/src." >&2
  echo "" >&2
  echo "  Files that changed after rebuilding from source:" >&2
  printf "%s\n" "$plugin_status" | sed 's/^/    /' >&2
  echo "" >&2
  echo "  plugins/lisa and plugins/lisa-* are GENERATED from plugins/src by" >&2
  echo "  'bun run build:plugins'. Never edit them directly — the next build" >&2
  echo "  overwrites the change." >&2
  echo "" >&2
  echo "  Fix:" >&2
  echo "    1. Make your edit under plugins/src/<base|stack|standalone (e.g. wiki)>/..." >&2
  echo "    2. Run: bun run build:plugins" >&2
  echo "    3. Commit both plugins/src and the regenerated plugins/lisa*." >&2
  # Leave the tree dirty so the diff is inspectable locally; CI fails on exit.
  exit 1
fi

echo "✓ Plugin artifacts are in sync with plugins/src."

# The same build writes well OUTSIDE plugins/ — the shared ESM entry guard and
# child-start deadline into three stack lanes, the threshold-ratchet trio into
# two, the host enforcement guards, the Sonar wrapper, and the fallback
# dispatcher. Until #3064 none of them was reproducibility-checked, so a
# maintainer who edited a generated copy directly, or edited a canonical and
# forgot to rebuild, got no signal from the check whose name says it covers what
# the plugin build produces.
#
# The path set is DERIVED, never listed: build-plugins.sh records each
# destination it actually writes into plugins/materialized-artifacts.json, so a
# materialize call added tomorrow is covered without touching this file. A
# second hand-maintained list is exactly what let these drift, and would rot the
# same way.
#
# By here the manifest exists and matches the committed one — the set-change
# check above proved both. What is left is the contents of each destination.
generated_files=()
while IFS= read -r generated_path; do
  if [ -n "$generated_path" ]; then
    generated_files+=("$generated_path")
  fi
done < <(jq -r '.[]' "$MATERIALIZED_MANIFEST")

# An empty inspection and a clean tree are otherwise indistinguishable: both
# print a tick. Refuse the empty one.
if [ "${#generated_files[@]}" -eq 0 ]; then
  echo "✗ The build recorded ZERO generated files outside plugins/." >&2
  echo "" >&2
  echo "  This check cannot pass by inspecting nothing. Every materialize call" >&2
  echo "  in build-plugins.sh is guarded on its source and its generator being" >&2
  echo "  present, so a missing scripts/materialize-copy-overwrite.mjs or a" >&2
  echo "  moved source silently skips the whole set." >&2
  echo "" >&2
  echo "  Fix: run 'bun run build:plugins' and confirm" >&2
  echo "  plugins/materialized-artifacts.json lists the destinations again." >&2
  exit 1
fi

# A destination git does not track can never be compared, so an untracked or
# gitignored one would be permanently invisible to the diff below — a green
# check over a file nobody is checking.
untracked_generated="$(
  comm -23 \
    <(printf "%s\n" "${generated_files[@]}" | LC_ALL=C sort) \
    <(git ls-files -- "${generated_files[@]}" | LC_ALL=C sort)
)"
if [ -n "$untracked_generated" ]; then
  echo "✗ Generated files outside plugins/ are not tracked by git." >&2
  echo "" >&2
  printf "%s\n" "$untracked_generated" | sed 's/^/    /' >&2
  echo "" >&2
  echo "  build-plugins.sh writes these, so they must be committed for this" >&2
  echo "  check to compare them. If one is newly generated, 'git add' it. If one" >&2
  echo "  is matched by .gitignore, the ignore rule is hiding a generated" >&2
  echo "  artifact and is the thing to fix." >&2
  exit 1
fi

generated_status="$(git status --porcelain -- "${generated_files[@]}")"
if [ -n "$generated_status" ]; then
  echo "✗ Generated files outside plugins/ are out of sync with their sources." >&2
  echo "" >&2
  echo "  Files that changed after rebuilding from source:" >&2
  printf "%s\n" "$generated_status" | sed 's/^/    /' >&2
  echo "" >&2
  echo "  These are GENERATED by 'bun run build:plugins' from a canonical source" >&2
  echo "  elsewhere in the tree — plugins/src/base/hooks/ or scripts/. Never edit" >&2
  echo "  them directly; the next build overwrites the change." >&2
  echo "" >&2
  echo "  Fix:" >&2
  echo "    1. Make your edit in the canonical source, not the generated copy." >&2
  echo "    2. Run: bun run build:plugins" >&2
  echo "    3. Commit the regenerated copies." >&2
  # Leave the tree dirty so the diff is inspectable locally; CI fails on exit.
  exit 1
fi

echo "✓ ${#generated_files[@]} generated files outside plugins/ match their sources."

# Marketplace coverage: every built plugin directory (plugins/lisa, plugins/lisa-*)
# must be registered in .claude-plugin/marketplace.json, and every marketplace
# entry must point at a directory that exists. The reproducibility check above
# only proves artifacts match plugins/src — it does NOT prove a built plugin is
# actually published. lisa-harper-fabric shipped built-but-unpublished for
# exactly this reason: install-claude-plugins.sh tried "lisa-harper-fabric@lisa"
# but the marketplace never advertised it, so resolution failed at install time.
MARKETPLACE="$ROOT_DIR/.claude-plugin/marketplace.json"
marketplace_fail=0

# Every built plugin dir needs a marketplace entry whose source points to it.
while IFS= read -r dir; do
  name="$(basename "$dir")"
  if ! jq -e --arg src "./plugins/$name" '.plugins[] | select(.source == $src)' "$MARKETPLACE" >/dev/null; then
    echo "✗ Built plugin plugins/$name is not registered in .claude-plugin/marketplace.json (expected source \"./plugins/$name\")." >&2
    marketplace_fail=1
  fi
done < <(find "$ROOT_DIR/plugins" -maxdepth 1 -mindepth 1 -type d ! -name src | sort)

# Every marketplace entry must point at a directory that exists.
while IFS= read -r src; do
  if [ ! -d "$ROOT_DIR/$src" ]; then
    echo "✗ marketplace.json entry source \"$src\" does not exist as a built plugin directory." >&2
    marketplace_fail=1
  fi
done < <(jq -r '.plugins[].source' "$MARKETPLACE")

if [ "$marketplace_fail" -ne 0 ]; then
  echo "" >&2
  echo "  Every plugins/lisa* directory must be registered in .claude-plugin/marketplace.json" >&2
  echo "  and every marketplace source must point to a real built directory. Edit the manifest" >&2
  echo "  at .claude-plugin/marketplace.json, then re-run: bun run check:plugins" >&2
  exit 1
fi

echo "✓ Marketplace registers every built plugin."
