#!/usr/bin/env bash
# Claude Code remote-routine setup for CodySwannGT/lisa.
# Generated by /lisa:generate-claude-remote-build-script from /lisa:analyze-claude-remote.
# Paste into your routine environment's setup-script field (or point it at
# `bash scripts/claude-remote-setup.sh`). Re-runnable, idempotent, detect-before-install.
#
# ─────────────────────────────────────────────────────────────────────────────
# GAPS this script CANNOT fix (handle separately):
#   - Auto-memory is machine-local and is NOT synced to cloud routines. Promote any
#     load-bearing memories into committed .claude/rules/.
#   - bun package fetch has known issues behind the cloud proxy (retried below).
#   - OS keychain is absent in the cloud — provide secrets as env vars (below), not keychain.
#   - linear-server MCP is OAuth (browser) → unusable headless. Dormant here (tracker=github);
#     if you switch to Linear, use LINEAR_API_KEY + Linear GraphQL instead.
#
# Already provided by committed .claude/settings.json env (applied automatically — do NOT re-enter in the UI):
#     - CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS, ENABLE_LSP_TOOL, BASH_DEFAULT_TIMEOUT_MS, BASH_MAX_TIMEOUT_MS
#
# SECRETS to set in the environment config (names only — set real values in the UI, NOT here):
#   Credentials for the active tracker/source (tracker=github, source=github):
#     # Acquire: https://github.com/settings/personal-access-tokens
#     # Access:  fine-grained PAT on CodySwannGT/lisa — Contents R/W, Issues R/W,
#     #          Pull requests R/W, Metadata R (+Workflows R/W if editing .github/workflows,
#     #          +Projects R/W if using ProjectV2). Identity needs WRITE+ on the repo.
#     - GH_TOKEN=<token>        # REQUIRED unless the routine's repo connection already auths `gh`
#   Dormant (set ONLY if you switch .lisa.config.json tracker/source):
#     - JIRA_API_TOKEN / JIRA_SERVER / JIRA_LOGIN / JIRA_PROJECT   # tracker=jira
#     - ATLASSIAN_API_TOKEN                                        # source=confluence (8 Confluence scopes)
#     - NOTION_API_TOKEN                                           # source=notion (share the PRD DB)
#     - LINEAR_API_KEY                                             # tracker/source=linear
#
# NETWORK: if the environment is not on full network access, allowlist:
#     - github.com
#     - objects.githubusercontent.com
#     - bun.sh
#     - playwright.azureedge.net   (only with --include-optional / Chromium)
# ─────────────────────────────────────────────────────────────────────────────

set -uo pipefail

INCLUDE_OPTIONAL=0
[ "${1:-}" = "--include-optional" ] && INCLUDE_OPTIONAL=1

need()    { command -v "$1" >/dev/null 2>&1; }
require() { need "$1" || { echo "FATAL: required tool '$1' missing and install failed" >&2; exit 1; }; }
apt_get() { sudo apt-get "$@" 2>/dev/null || apt-get "$@"; }

# --- package manager: bun (REQUIRED) ---
if ! need bun; then
  echo "Installing bun..."
  curl -fsSL https://bun.sh/install | bash
fi
export PATH="$HOME/.bun/bin:$PATH"
require bun

# --- required CLIs ---
if ! need jq; then
  echo "Installing jq..."
  apt_get update -y && apt_get install -y jq
fi
if ! need gh; then
  echo "Installing gh..."
  apt_get update -y && apt_get install -y gh \
    || { type -p curl >/dev/null && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
         | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
         && echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
         | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null \
         && apt_get update -y && apt_get install -y gh; }
fi
require jq
require gh

# --- gitleaks (REQUIRED: pre-commit secret scan) ---
if ! need gitleaks; then
  echo "Installing gitleaks..."
  GITLEAKS_VERSION="8.18.4"
  curl -sSfL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" \
    | sudo tar -xz -C /usr/local/bin gitleaks
fi
require gitleaks

# --- project dependencies ---
# bun has known proxy package-fetch issues in cloud sessions; retry transient failures.
if [ ! -d node_modules ]; then
  echo "Installing project dependencies (bun install)..."
  for i in 1 2 3; do bun install && break || { echo "bun install attempt $i failed; retrying..."; sleep 5; }; done
fi
[ -d node_modules ] || { echo "FATAL: bun install failed after retries" >&2; exit 1; }

# --- OPTIONAL (only with --include-optional; dormant stacks/integrations) ---
if [ "$INCLUDE_OPTIONAL" = "1" ]; then
  echo "Installing optional tooling..."

  # jira-cli (only if tracker=jira)
  if ! need jira; then
    JIRA_CLI_VERSION="1.7.0"
    TMP=$(mktemp -d)
    curl -sSfL "https://github.com/ankitpokhrel/jira-cli/releases/download/v${JIRA_CLI_VERSION}/jira_${JIRA_CLI_VERSION}_linux_x86_64.tar.gz" \
      | tar -xz -C "$TMP" \
      && sudo cp "$TMP/jira_${JIRA_CLI_VERSION}_linux_x86_64/bin/jira" /usr/local/bin/jira \
      && sudo chmod +x /usr/local/bin/jira
    rm -rf "$TMP"
  fi

  # Chromium for Lighthouse/Playwright (heavy — can strain the cache budget)
  npx playwright install chromium || echo "WARN: chromium install failed (optional)"

  # aws CLI (cleanup scripts)
  need aws || apt_get install -y awscli || echo "WARN: awscli install failed (optional)"
fi

echo "claude-remote-setup: done."
