/**
 * Test-owned materialized environment artifact shapes for remote SessionStart.
 *
 * Keeping shell-format construction separate from the process harness makes
 * both helpers reviewable while retaining one exact writer-shaped fixture.
 * @module tests/helpers/remote-env-materialized-artifact
 */
import { chmodSync, mkdirSync, symlinkSync, writeFileSync } from "node:fs";
import path from "node:path";

/** Artifact states the SessionStart reader must adjudicate. */
export type MaterializedArtifactKind =
  | "valid"
  | "missing"
  | "unreadable"
  | "file-mode"
  | "directory-mode"
  | "file-symlink"
  | "directory-symlink"
  | "not-regular"
  | "invalid-command"
  | "truncated";

/** A value whose shell punctuation must remain literal. */
export const HOSTILE_VALUE = `fresh $(touch SHOULD_NOT_RUN) ${String.fromCharCode(
  96
)}id${String.fromCharCode(96)} 'quoted' spaces ; $HOME`;

/** Minimum paths needed to construct one artifact arm. */
interface ArtifactFixture {
  readonly configRoot: string;
  readonly hostileEffect: string;
  readonly root: string;
  readonly value: string;
  readonly valuesFile: string;
}

/**
 * Quote one value exactly as Lisa's envfile writer does.
 * @param value - Secret fixture value whose shell meaning must stay inert.
 * @returns Single-quoted shell text matching the production writer.
 */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/**
 * Text written by the real materializer for one selected secret.
 * @param value - Secret fixture value written into the artifact.
 * @returns Complete production-shaped materialized environment text.
 */
function validArtifact(value: string): string {
  return [
    "# Generated by lisa-secrets-access. Contains secret values.",
    "# Do not print, inspect, summarize, commit, or copy this file.",
    `export LISA_FRESH_SECRET=${shellQuote(value)}`,
    "",
  ].join("\n");
}

/**
 * Create the exact directory/file shape selected by one negative arm.
 * @param fixture - Isolated paths and values owned by the current test arm.
 * @param kind - Artifact state the SessionStart boundary must adjudicate.
 */
export function writeMaterializedArtifact(
  fixture: ArtifactFixture,
  kind: MaterializedArtifactKind
): void {
  const namespaceDir = path.dirname(fixture.valuesFile);
  const content =
    kind === "invalid-command"
      ? `${validArtifact(fixture.value)}printf compromised > ${shellQuote(
          fixture.hostileEffect
        )}\n`
      : kind === "truncated"
        ? "export LISA_FRESH_SECRET='unterminated\n"
        : validArtifact(fixture.value);
  mkdirSync(fixture.configRoot, { recursive: true, mode: 0o700 });
  if (kind === "directory-symlink") {
    const target = path.join(fixture.root, "foreign-namespace");
    mkdirSync(target, { recursive: true, mode: 0o700 });
    writeFileSync(
      path.join(target, "secrets.env"),
      validArtifact(fixture.value),
      { mode: 0o600 }
    );
    symlinkSync(target, namespaceDir);
    return;
  }
  mkdirSync(namespaceDir, { recursive: true, mode: 0o700 });
  if (kind === "missing") return;
  if (kind === "not-regular") {
    mkdirSync(fixture.valuesFile, { mode: 0o700 });
    return;
  }
  if (kind === "file-symlink") {
    const target = path.join(fixture.root, "foreign-secrets.env");
    writeFileSync(target, validArtifact(fixture.value), { mode: 0o600 });
    symlinkSync(target, fixture.valuesFile);
    return;
  }
  writeFileSync(fixture.valuesFile, content, { mode: 0o600 });
  if (kind === "unreadable") chmodSync(fixture.valuesFile, 0o000);
  if (kind === "file-mode") chmodSync(fixture.valuesFile, 0o644);
  if (kind === "directory-mode") chmodSync(namespaceDir, 0o755);
}
